import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Activity, ArrowLeft, CalendarDays, Check, ChevronRight, Clock3, FileText, Flame, Gift, GraduationCap, Mail, Phone, Plus, ReceiptText, ShoppingBag, Target, Trophy, X } from 'lucide-react-native';

import { AdminShell } from '@/components/admin-shell';
import { font, radius, spacing } from '@/constants/theme';
import { useAdminAccessStore } from '@/lib/admin-access-store';
import { adminStudents, formatInr, ordersForStudent, paidNotes } from '@/lib/demo-admin';
import { useAppTheme } from '@/providers/app-providers';

export default function AdminStudentDetail() {
  const { theme } = useAppTheme();
  const router = useRouter();
  const params = useLocalSearchParams<{ id: string }>();
  const student = adminStudents.find((item) => item.id === params.id) ?? adminStudents[0];
  const orders = ordersForStudent(student.id);
  const totalSpent = orders.filter((order) => order.status === 'Paid').reduce((total, order) => total + order.amount, 0);
  const initials = student.name.split(' ').map((part) => part[0]).slice(0, 2).join('');
  const [showGrantSheet, setShowGrantSheet] = useState(false);
  const [selectedNoteId, setSelectedNoteId] = useState<string | null>(null);
  const grants = useAdminAccessStore((state) => state.grants);
  const grantNote = useAdminAccessStore((state) => state.grantNote);
  const revokeNote = useAdminAccessStore((state) => state.revokeNote);
  const studentGrants = grants.filter((grant) => grant.studentId === student.id);
  const grantedIds = new Set(studentGrants.map((grant) => grant.noteId));
  const purchasedTitles = new Set(orders.filter((order) => order.itemType === 'Note' && order.status === 'Paid').map((order) => order.item));
  const eligibleNotes = paidNotes.filter((note) => note.course === student.course && note.category === student.category && !purchasedTitles.has(note.title));
  const grantableNotes = eligibleNotes.filter((note) => !grantedIds.has(note.id));

  const openGrantSheet = () => { setSelectedNoteId(grantableNotes[0]?.id ?? null); setShowGrantSheet(true); };
  const confirmGrant = () => { if (!selectedNoteId) return; grantNote(student.id, selectedNoteId); setSelectedNoteId(null); setShowGrantSheet(false); };
  const back = <Pressable accessibilityRole="button" accessibilityLabel="Back to students" onPress={() => router.back()} style={[styles.back, { backgroundColor: theme.surface, borderColor: theme.line }]}><ArrowLeft size={18} color={theme.fg} /></Pressable>;

  return <>
    <AdminShell eyebrow="STUDENT PROFILE" title={student.name} description={`${student.course} · ${student.category} · joined ${student.joinedOn}`} action={back}>
      <LinearGradient colors={['#1B2543', '#111725', '#101318']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.profileHero}>
        <View style={styles.heroOrbit} />
        <View style={styles.profileTop}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><View style={styles.profileCopy}><Text style={styles.profileName}>{student.name}</Text><Text style={styles.profileId}>{student.id} · Active {student.lastActive}</Text></View><View style={styles.coursePill}><Text style={styles.courseText}>{student.course} · {student.category}</Text></View></View>
        <View style={styles.contactStrip}><View style={styles.contactItem}><Mail size={14} color="#AEB8D8" /><Text numberOfLines={1} style={styles.contactText}>{student.email}</Text></View><View style={styles.contactItem}><Phone size={14} color="#AEB8D8" /><Text numberOfLines={1} style={styles.contactText}>{student.phone}</Text></View></View>
      </LinearGradient>

      <View style={[styles.focusSummary, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.focusIcon, { backgroundColor: theme.primarySoft }]}><Clock3 size={20} color={theme.primaryStrong} /></View><View style={styles.profileCopy}><Text style={[styles.cardEyebrow, { color: theme.primary }]}>TOTAL FOCUS</Text><Text style={[styles.focusValue, { color: theme.fg }]}>{student.hoursStudied} hours</Text><Text style={[styles.cardDetail, { color: theme.muted }]}>Lifetime study activity recorded</Text></View><View style={[styles.focusStatus, { backgroundColor: theme.successSoft }]}><Activity size={13} color={theme.success} /><Text style={[styles.focusStatusText, { color: theme.success }]}>ACTIVE</Text></View></View>

      <View style={styles.metricGrid}><View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><ShoppingBag size={17} color={theme.goldStrong} /><Text style={[styles.metricValue, { color: theme.fg }]}>{orders.length}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>Orders placed</Text></View><View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><ReceiptText size={17} color={theme.success} /><Text adjustsFontSizeToFit numberOfLines={1} style={[styles.metricValue, { color: theme.fg }]}>{formatInr(totalSpent)}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>Total spent</Text></View></View>

      <View style={[styles.learningCard, { backgroundColor: theme.surface, borderColor: theme.line }]}>
        <View style={styles.cardHeading}><View style={[styles.learningIcon, { backgroundColor: theme.goldSoft }]}><GraduationCap size={20} color={theme.goldStrong} /></View><View style={styles.profileCopy}><Text style={[styles.cardEyebrow, { color: theme.goldStrong }]}>LEARNING PLAN</Text><Text style={[styles.cardTitle, { color: theme.fg }]}>{student.course} · {student.category}</Text></View></View>
        <View style={[styles.detailGrid, { borderTopColor: theme.line }]}><ProfileFact icon={CalendarDays} label="Exam date" value={student.examDate} /><ProfileFact icon={Target} label="Daily target" value={student.dailyTarget} /><ProfileFact icon={GraduationCap} label="Academy ID" value={student.academyId ?? 'Not provided'} /></View>
      </View>

      <View style={[styles.progressCard, { backgroundColor: theme.surface, borderColor: theme.line }]}>
        <View style={styles.cardHeading}><View><Text style={[styles.cardEyebrow, { color: theme.primary }]}>STUDY SIGNALS</Text><Text style={[styles.cardTitle, { color: theme.fg }]}>Current learning rhythm</Text></View></View>
        <View style={styles.signalRow}><Signal icon={Flame} value={`${student.streakDays}d`} label="Streak" color={theme.goldStrong} /><View style={[styles.signalDivider, { backgroundColor: theme.line }]} /><Signal icon={Target} value={`${student.syllabusCompletion}%`} label="Syllabus" color={theme.primaryStrong} /><View style={[styles.signalDivider, { backgroundColor: theme.line }]} /><Signal icon={Trophy} value={`${student.practiceAccuracy}%`} label="Accuracy" color={theme.success} /></View>
        <View style={[styles.progressTrack, { backgroundColor: theme.sunken }]}><View style={[styles.progressFill, { width: `${student.syllabusCompletion}%`, backgroundColor: theme.primary }]} /></View>
      </View>

      <View style={styles.sectionHeading}><View style={styles.sectionCopy}><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>ACCESS</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>Complimentary notes</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>{studentGrants.length ? `${studentGrants.length} notes granted free` : 'Give a course-relevant paid note for free'}</Text></View><Pressable disabled={!grantableNotes.length} accessibilityRole="button" accessibilityLabel="Grant free note access" onPress={openGrantSheet} style={({ pressed }) => [styles.grantButton, { backgroundColor: theme.primary }, !grantableNotes.length && styles.disabled, pressed && styles.pressed]}>{grantableNotes.length ? <Plus size={15} color={theme.primaryFg} /> : <Check size={15} color={theme.primaryFg} />}<Text style={[styles.grantButtonText, { color: theme.primaryFg }]}>{grantableNotes.length ? 'Grant' : 'Assigned'}</Text></Pressable></View>
      {studentGrants.length ? <View style={styles.list}>{studentGrants.map((grant) => { const note = paidNotes.find((item) => item.id === grant.noteId); if (!note) return null; return <View key={grant.id} style={[styles.accessRow, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.rowIcon, { backgroundColor: theme.successSoft }]}><Gift size={17} color={theme.success} /></View><View style={styles.orderCopy}><Text numberOfLines={1} style={[styles.orderTitle, { color: theme.fg }]}>{note.title}</Text><Text numberOfLines={1} style={[styles.orderMeta, { color: theme.muted }]}>{note.subject} · {note.pages} pages · Granted {grant.grantedAt}</Text></View><View style={[styles.freePill, { backgroundColor: theme.successSoft }]}><Text style={[styles.freeText, { color: theme.success }]}>FREE</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Revoke free access to ${note.title}`} onPress={() => revokeNote(student.id, note.id)} style={[styles.revoke, { backgroundColor: theme.sunken }]}><X size={14} color={theme.muted} /></Pressable></View>; })}</View> : <View style={[styles.emptyAccess, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.emptyAccessIcon, { backgroundColor: theme.primarySoft }]}><Gift size={19} color={theme.primaryStrong} /></View><View style={styles.sectionCopy}><Text style={[styles.emptyAccessTitle, { color: theme.fg }]}>No complimentary notes</Text><Text style={[styles.emptyAccessCopy, { color: theme.muted }]}>Use Grant to assign a relevant note without a purchase.</Text></View></View>}

      <View style={styles.sectionHeading}><View><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>COMMERCE</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>Order history</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>{orders.length ? `${orders.length} receipts available` : 'No orders placed'}</Text></View></View>
      <View style={styles.list}>{orders.map((order) => <Pressable key={order.id} onPress={() => router.push({ pathname: '/admin/orders/[id]' as never, params: { id: order.id } })} style={({ pressed }) => [styles.orderRow, { backgroundColor: theme.surface, borderColor: theme.line }, pressed && styles.pressed]}><View style={[styles.rowIcon, { backgroundColor: order.itemType === 'Package' ? theme.goldSoft : theme.primarySoft }]}><ReceiptText size={17} color={order.itemType === 'Package' ? theme.goldStrong : theme.primaryStrong} /></View><View style={styles.orderCopy}><Text numberOfLines={1} style={[styles.orderTitle, { color: theme.fg }]}>{order.item}</Text><Text style={[styles.orderMeta, { color: theme.muted }]}>{order.id} · {order.date}</Text></View><View style={styles.orderAmount}><Text style={[styles.amount, { color: theme.fg }]}>{formatInr(order.amount)}</Text><Text style={[styles.paid, { color: order.status === 'Paid' ? theme.success : theme.danger }]}>{order.status}</Text></View><ChevronRight size={16} color={theme.faint} /></Pressable>)}</View>
    </AdminShell>

    <Modal visible={showGrantSheet} transparent animationType="none" onRequestClose={() => setShowGrantSheet(false)}><View style={styles.modalRoot}><Pressable accessibilityRole="button" accessibilityLabel="Close free access picker" style={styles.backdrop} onPress={() => setShowGrantSheet(false)} /><View style={[styles.sheet, { backgroundColor: theme.elevated, borderColor: theme.lineStrong }]}>
      <View style={[styles.sheetHandle, { backgroundColor: theme.lineStrong }]} /><View style={styles.sheetHeader}><View style={styles.sectionCopy}><Text style={[styles.sheetEyebrow, { color: theme.primary }]}>COMPLIMENTARY ACCESS</Text><Text style={[styles.sheetTitle, { color: theme.fg }]}>Choose a note</Text><Text style={[styles.sheetCopy, { color: theme.muted }]}>Available {student.course} · {student.category} notes for {student.name}.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={() => setShowGrantSheet(false)} style={[styles.sheetClose, { backgroundColor: theme.sunken }]}><X size={18} color={theme.muted} /></Pressable></View>
      <ScrollView style={styles.notePickerScroll} contentContainerStyle={styles.notePicker} showsVerticalScrollIndicator={false}>{eligibleNotes.map((note) => { const granted = grantedIds.has(note.id); const selected = selectedNoteId === note.id; return <Pressable key={note.id} disabled={granted} accessibilityRole="radio" accessibilityState={{ checked: selected, disabled: granted }} onPress={() => setSelectedNoteId(note.id)} style={[styles.noteOption, { backgroundColor: selected ? theme.primarySoft : theme.surface, borderColor: selected ? theme.primary : theme.line }, granted && styles.grantedOption]}><View style={[styles.noteOptionIcon, { backgroundColor: granted ? theme.successSoft : theme.sunken }]}>{granted ? <Check size={17} color={theme.success} strokeWidth={3} /> : <FileText size={17} color={selected ? theme.primaryStrong : theme.muted} />}</View><View style={styles.orderCopy}><Text numberOfLines={1} style={[styles.noteTitle, { color: theme.fg }]}>{note.title}</Text><Text style={[styles.noteMeta, { color: theme.muted }]}>{note.subject} · {note.pages} pages · {formatInr(note.price)}</Text></View>{granted ? <Text style={[styles.grantedText, { color: theme.success }]}>GRANTED</Text> : <View style={[styles.radio, { borderColor: selected ? theme.primary : theme.faint, backgroundColor: selected ? theme.primary : 'transparent' }]}>{selected ? <Check size={12} color={theme.primaryFg} strokeWidth={3} /> : null}</View>}</Pressable>; })}{!eligibleNotes.length ? <View style={[styles.noNotes, { backgroundColor: theme.surface }]}><Text style={[styles.emptyAccessTitle, { color: theme.fg }]}>No eligible notes</Text><Text style={[styles.emptyAccessCopy, { color: theme.muted }]}>All matching notes are already purchased or assigned.</Text></View> : null}</ScrollView>
      <Pressable disabled={!selectedNoteId} accessibilityRole="button" onPress={confirmGrant} style={({ pressed }) => [styles.confirmButton, { backgroundColor: theme.primary }, !selectedNoteId && styles.disabled, pressed && styles.pressed]}><Gift size={17} color={theme.primaryFg} /><Text style={[styles.confirmText, { color: theme.primaryFg }]}>Grant free access</Text></Pressable>
    </View></View></Modal>
  </>;
}

function ProfileFact({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { const { theme } = useAppTheme(); return <View style={styles.fact}><Icon size={15} color={theme.primaryStrong} /><View style={styles.factCopy}><Text style={[styles.factLabel, { color: theme.muted }]}>{label}</Text><Text numberOfLines={1} style={[styles.factValue, { color: theme.fg }]}>{value}</Text></View></View>; }
function Signal({ icon: Icon, value, label, color }: { icon: typeof Flame; value: string; label: string; color: string }) { const { theme } = useAppTheme(); return <View style={styles.signal}><Icon size={17} color={color} /><Text style={[styles.signalValue, { color: theme.fg }]}>{value}</Text><Text style={[styles.signalLabel, { color: theme.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({
  back: { width: 38, height: 38, borderWidth: 1, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  profileHero: { minHeight: 152, borderRadius: 20, padding: 14, overflow: 'hidden', justifyContent: 'space-between' }, heroOrbit: { position: 'absolute', width: 160, height: 160, borderRadius: 80, borderWidth: 1, borderColor: 'rgba(255,255,255,.08)', right: -60, top: -66 },
  profileTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 52, height: 52, borderRadius: 17, backgroundColor: 'rgba(159,179,255,.18)', borderWidth: 1, borderColor: 'rgba(199,210,255,.25)', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#DCE3FF', fontFamily: font.extraBold, fontSize: 15 }, profileCopy: { flex: 1, minWidth: 0 }, profileName: { color: '#FFF', fontFamily: font.extraBold, fontSize: 16 }, profileId: { marginTop: 3, color: '#AEB8D8', fontFamily: font.regular, fontSize: 8 }, coursePill: { maxWidth: '38%', minHeight: 27, borderRadius: radius.pill, backgroundColor: 'rgba(159,179,255,.13)', paddingHorizontal: 8, alignItems: 'center', justifyContent: 'center' }, courseText: { color: '#C7D2FF', fontFamily: font.bold, fontSize: 7 },
  contactStrip: { minHeight: 44, marginTop: 14, paddingTop: 11, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.10)', flexDirection: 'row', gap: 10 }, contactItem: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6 }, contactText: { flex: 1, color: '#D3D9EC', fontFamily: font.regular, fontSize: 8 },
  focusSummary: { minHeight: 92, borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, focusIcon: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, focusValue: { marginTop: 2, fontFamily: font.extraBold, fontSize: 18 }, focusStatus: { minHeight: 27, borderRadius: radius.pill, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 }, focusStatusText: { fontFamily: font.bold, fontSize: 7, letterSpacing: .6 },
  metricGrid: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, minWidth: 0, minHeight: 91, borderWidth: 1, borderRadius: 16, padding: 11 }, metricValue: { marginTop: 8, fontFamily: font.extraBold, fontSize: 17, letterSpacing: -.4 }, metricLabel: { marginTop: 2, fontFamily: font.medium, fontSize: 8 },
  learningCard: { borderWidth: 1, borderRadius: 18, padding: 13 }, cardHeading: { flexDirection: 'row', alignItems: 'center', gap: 9 }, learningIcon: { width: 41, height: 41, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, cardEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1 }, cardTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 14 }, cardDetail: { marginTop: 2, fontFamily: font.regular, fontSize: 8 },
  detailGrid: { marginTop: 12, paddingTop: 11, borderTopWidth: 1, gap: 9 }, fact: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 8 }, factCopy: { flex: 1, minWidth: 0 }, factLabel: { fontFamily: font.regular, fontSize: 7 }, factValue: { marginTop: 2, fontFamily: font.bold, fontSize: 10 },
  progressCard: { borderWidth: 1, borderRadius: 18, padding: 13 }, signalRow: { marginTop: 15, flexDirection: 'row', alignItems: 'center' }, signal: { flex: 1, alignItems: 'center' }, signalValue: { marginTop: 5, fontFamily: font.extraBold, fontSize: 15 }, signalLabel: { marginTop: 2, fontFamily: font.regular, fontSize: 7 }, signalDivider: { width: 1, height: 42 }, progressTrack: { height: 6, marginTop: 14, borderRadius: 3, overflow: 'hidden' }, progressFill: { height: '100%', borderRadius: 3 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 9 }, sectionCopy: { flex: 1, minWidth: 0 }, sectionEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.05 }, sectionTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 16 }, sectionHint: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, grantButton: { minHeight: 35, borderRadius: 11, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, grantButtonText: { fontFamily: font.bold, fontSize: 9 }, list: { gap: spacing.sm },
  accessRow: { minHeight: 72, borderWidth: 1, borderRadius: 15, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, rowIcon: { width: 37, height: 37, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, freePill: { minHeight: 23, borderRadius: radius.pill, paddingHorizontal: 7, alignItems: 'center', justifyContent: 'center' }, freeText: { fontFamily: font.bold, fontSize: 7, letterSpacing: .6 }, revoke: { width: 29, height: 29, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  emptyAccess: { minHeight: 79, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, emptyAccessIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, emptyAccessTitle: { fontFamily: font.bold, fontSize: 11 }, emptyAccessCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8, lineHeight: 13 },
  orderRow: { minHeight: 71, borderWidth: 1, borderRadius: 15, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, orderCopy: { flex: 1, minWidth: 0 }, orderTitle: { fontFamily: font.bold, fontSize: 10 }, orderMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, orderAmount: { alignItems: 'flex-end' }, amount: { fontFamily: font.bold, fontSize: 10 }, paid: { marginTop: 3, fontFamily: font.bold, fontSize: 7 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, backdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(0,0,0,.72)' }, sheet: { width: '100%', maxWidth: 680, maxHeight: '82%', alignSelf: 'center', borderWidth: 1, borderBottomWidth: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing.lg, paddingBottom: 25 }, sheetHandle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 13 }, sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, sheetEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.1 }, sheetTitle: { marginTop: 4, fontFamily: font.extraBold, fontSize: 18 }, sheetCopy: { marginTop: 4, fontFamily: font.regular, fontSize: 9, lineHeight: 14 }, sheetClose: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, notePickerScroll: { marginTop: 14 }, notePicker: { gap: 8, paddingBottom: 2 }, noteOption: { minHeight: 65, borderWidth: 1, borderRadius: 14, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 8 }, grantedOption: { opacity: .68 }, noteOptionIcon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, noteTitle: { fontFamily: font.bold, fontSize: 10 }, noteMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, radio: { width: 21, height: 21, borderRadius: 11, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, grantedText: { fontFamily: font.bold, fontSize: 7 }, noNotes: { minHeight: 80, borderRadius: 14, padding: 13, justifyContent: 'center' }, confirmButton: { minHeight: 45, marginTop: 14, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, confirmText: { fontFamily: font.bold, fontSize: 10 }, disabled: { opacity: .42 }, pressed: { opacity: .74, transform: [{ scale: .99 }] },
});
