import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, CheckCircle2, LockKeyhole, ShieldCheck } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton, Card } from '@/components/ui';
import { font, spacing } from '@/constants/theme';
import { findLesson } from '@/lib/demo-catalog';
import { useAppTheme } from '@/providers/app-providers';

export default function PurchaseScreen() { const { id } = useLocalSearchParams(); const { lesson, subject } = findLesson(id); const router = useRouter(); const { theme } = useAppTheme(); const [purchased, setPurchased] = useState(false); if (purchased) return <SafeAreaView style={[styles.safe, { backgroundColor: theme.canvas }]}><View style={styles.successWrap}><View style={[styles.successIcon, { backgroundColor: theme.successSoft }]}><CheckCircle2 color={theme.success} size={45} /></View><Text style={[styles.successTitle, { color: theme.fg }]}>You own this lesson.</Text><Text style={[styles.successCopy, { color: theme.muted }]}>Constitutional access is now available in your protected Library.</Text><AppButton label="Open lesson" onPress={() => router.replace({ pathname: '/lesson/[id]', params: { id: lesson.id } })} /><AppButton label="Go to my Library" variant="secondary" onPress={() => router.replace('/library')} /></View></SafeAreaView>; return <SafeAreaView style={[styles.safe, { backgroundColor: theme.canvas }]}><View style={styles.content}><Pressable onPress={() => router.back()} style={[styles.back, { borderColor: theme.line, backgroundColor: theme.surface }]}><ArrowLeft color={theme.fg} size={20} /></Pressable><View style={[styles.hero, { backgroundColor: theme.primary }]}><View style={styles.lock}><LockKeyhole color="#D8BC86" size={26} /></View><Text style={styles.eyebrow}>ONE-TIME PURCHASE</Text><Text style={styles.title}>{lesson.title}</Text><Text style={styles.subject}>{subject.title} · {lesson.pages} pages</Text></View><Card><Text style={[styles.cardTitle, { color: theme.fg }]}>What you get</Text><View style={styles.points}>{['Protected access for life', 'Completion and revision tracking', 'Personalised secure reader'].map((point) => <View key={point} style={styles.point}><CheckCircle2 color={theme.success} size={18} /><Text style={[styles.pointText, { color: theme.muted }]}>{point}</Text></View>)}</View><View style={[styles.priceRow, { borderTopColor: theme.line }]}><Text style={[styles.priceLabel, { color: theme.muted }]}>Lesson price</Text><Text style={[styles.price, { color: theme.fg }]}>{lesson.price ?? '₹79'}</Text></View><AppButton label="Continue to checkout" variant="gold" onPress={() => setPurchased(true)} /><Text style={[styles.disclaimer, { color: theme.muted }]}>UI demo only — no payment is processed.</Text></Card><View style={styles.safeNotice}><ShieldCheck color={theme.primary} size={17} /><Text style={[styles.safeText, { color: theme.muted }]}>Your lesson opens in Parallax Flow’s protected reader.</Text></View></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: spacing.lg, gap: spacing.lg, maxWidth: 680, alignSelf: 'center', width: '100%' }, successWrap: { flex: 1, padding: 28, gap: 14, justifyContent: 'center', maxWidth: 500, width: '100%', alignSelf: 'center' }, successIcon: { width: 88, height: 88, borderRadius: 44, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, successTitle: { fontFamily: font.extraBold, fontSize: 27, textAlign: 'center' }, successCopy: { fontFamily: font.regular, fontSize: 14, lineHeight: 21, textAlign: 'center', marginBottom: 6 }, back: { height: 42, width: 42, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, hero: { borderRadius: 20, padding: 22, minHeight: 192 }, lock: { width: 50, height: 50, borderRadius: 15, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: '#D8BC86', fontFamily: font.bold, fontSize: 10, letterSpacing: 1.3, marginTop: 17 }, title: { color: '#FFFFFF', fontFamily: font.extraBold, fontSize: 25, lineHeight: 31, marginTop: 5 }, subject: { color: '#D5DCFD', fontFamily: font.regular, fontSize: 13, marginTop: 7 }, cardTitle: { fontFamily: font.bold, fontSize: 17 }, points: { gap: 13, marginTop: 12 }, point: { flexDirection: 'row', gap: 10, alignItems: 'center' }, pointText: { fontFamily: font.regular, fontSize: 13 }, priceRow: { borderTopWidth: 1, marginTop: 17, paddingTop: 14, flexDirection: 'row', justifyContent: 'space-between' }, priceLabel: { fontFamily: font.regular, fontSize: 13 }, price: { fontFamily: font.extraBold, fontSize: 22 }, disclaimer: { textAlign: 'center', fontFamily: font.regular, fontSize: 10 }, safeNotice: { flexDirection: 'row', alignItems: 'center', gap: 7, justifyContent: 'center' }, safeText: { fontFamily: font.regular, fontSize: 11 } });
