import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, CheckCircle2, ReceiptText } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton, Card } from '@/components/ui';
import { font, spacing } from '@/constants/theme';
import { orders } from '@/lib/demo-commerce';
import { useAppTheme } from '@/providers/app-providers';

export default function ReceiptScreen() { const { id } = useLocalSearchParams(); const order = orders.find((entry) => entry.id === id) ?? orders[0]; const router = useRouter(); const { theme } = useAppTheme(); return <SafeAreaView style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: theme.surface, borderColor: theme.line }]}><ArrowLeft size={20} color={theme.fg} /></Pressable><View style={styles.heading}><View style={[styles.receiptIcon, { backgroundColor: theme.primarySoft }]}><ReceiptText size={25} color={theme.primary} /></View><Text style={[styles.title, { color: theme.fg }]}>Receipt</Text><Text style={[styles.sub, { color: theme.muted }]}>A permanent record of your purchase.</Text></View><Card><View style={styles.paidRow}><View><Text style={[styles.receiptNumber, { color: theme.fg }]}>{order.id}</Text><Text style={[styles.date, { color: theme.muted }]}>{order.date}</Text></View><View style={[styles.status, { backgroundColor: theme.successSoft }]}><CheckCircle2 color={theme.success} size={15} /><Text style={[styles.statusText, { color: theme.success }]}>Paid</Text></View></View><View style={[styles.rule, { backgroundColor: theme.line }]} /><Text style={[styles.itemTitle, { color: theme.fg }]}>{order.items}</Text><Text style={[styles.itemSub, { color: theme.muted }]}>Secure lesson access · yours forever</Text><View style={[styles.total, { borderTopColor: theme.line }]}><Text style={[styles.totalLabel, { color: theme.muted }]}>Total paid</Text><Text style={[styles.totalAmount, { color: theme.fg }]}>{order.amount}</Text></View><Text style={[styles.reference, { color: theme.muted }]}>Payment reference: demo_ui_only</Text></Card><AppButton label="Save receipt" variant="secondary" onPress={() => undefined} /><Text style={[styles.note, { color: theme.muted }]}>UI demo only — saving a receipt will be connected after backend integration.</Text></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: spacing.lg, gap: spacing.lg, maxWidth: 680, width: '100%', alignSelf: 'center' }, back: { width: 42, height: 42, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, heading: { alignItems: 'center', gap: 5 }, receiptIcon: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, title: { fontFamily: font.extraBold, fontSize: 29 }, sub: { fontFamily: font.regular, fontSize: 13 }, paidRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, receiptNumber: { fontFamily: font.bold, fontSize: 16 }, date: { fontFamily: font.regular, fontSize: 12, marginTop: 3 }, status: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10 }, statusText: { fontFamily: font.bold, fontSize: 11 }, rule: { height: 1, marginVertical: 17 }, itemTitle: { fontFamily: font.bold, fontSize: 15 }, itemSub: { fontFamily: font.regular, fontSize: 12, marginTop: 4 }, total: { borderTopWidth: 1, marginTop: 18, paddingTop: 14, flexDirection: 'row', justifyContent: 'space-between' }, totalLabel: { fontFamily: font.regular, fontSize: 13 }, totalAmount: { fontFamily: font.extraBold, fontSize: 22 }, reference: { fontFamily: font.regular, fontSize: 10, marginTop: 12 }, note: { fontFamily: font.regular, fontSize: 10, textAlign: 'center' } });
