import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, CheckCircle2, ReceiptText } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton, Card } from '@/components/ui';
import { font, spacing } from '@/constants/theme';
import { useAuthStore } from '@/lib/auth-store';
import { orders } from '@/lib/demo-commerce';
import { getReceipt } from '@/lib/student-content-api';
import { isDemoSession } from '@/lib/student-session';
import { useAppTheme } from '@/providers/app-providers';

export default function ReceiptScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const demo = useAuthStore((state) => isDemoSession(state.accessToken, state.user?.id)); return demo ? <DemoReceipt id={id} /> : <RemoteReceipt id={id} />; }
function RemoteReceipt({ id }: { id: string }) { const router = useRouter(); const { theme } = useAppTheme(); const query = useQuery({ queryKey: ['student', 'receipt', id], queryFn: () => getReceipt(id) }); if (query.isLoading) return <SafeAreaView style={[styles.safe, styles.center, { backgroundColor: theme.canvas }]}><ActivityIndicator color={theme.primary} /></SafeAreaView>; if (!query.data) return <SafeAreaView style={[styles.safe, styles.center, { backgroundColor: theme.canvas }]}><Text style={[styles.sub, { color: theme.muted }]}>Receipt unavailable.</Text><AppButton label="Try again" onPress={() => query.refetch()} /></SafeAreaView>; const receipt = query.data; return <ReceiptLayout onBack={() => router.back()} title={receipt.receiptNumber ?? receipt.orderNumber} date={new Date(receipt.paidAt ?? receipt.createdAt).toLocaleDateString()} status={receipt.status} subtitle={`${receipt.purchaseType === 'FREE_PURCHASE' ? 'Complimentary purchase' : 'Paid purchase'} · ${receipt.course.name}`} items={receipt.items.map((item) => `${item.titleSnapshot} ×${item.quantity}`)} amount={money(receipt.totals.total?.amount ?? 0, receipt.totals.total?.currency ?? 'INR')} reference={`Order: ${receipt.orderNumber}`} />; }
function DemoReceipt({ id }: { id: string }) { const router = useRouter(); const order = orders.find((entry) => entry.id === id) ?? orders[0]; return <ReceiptLayout onBack={() => router.back()} title={order.id} date={order.date} status={order.status} subtitle="A permanent record of your purchase." items={[order.items]} amount={order.amount} reference="Demo receipt" />; }
function ReceiptLayout({ onBack, title, date, status, subtitle, items, amount, reference }: { onBack: () => void; title: string; date: string; status: string; subtitle: string; items: string[]; amount: string; reference: string }) { const { theme } = useAppTheme(); return <SafeAreaView style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={onBack} style={[styles.back, { backgroundColor: theme.surface, borderColor: theme.line }]}><ArrowLeft size={20} color={theme.fg} /></Pressable><View style={styles.heading}><View style={[styles.receiptIcon, { backgroundColor: theme.primarySoft }]}><ReceiptText size={25} color={theme.primary} /></View><Text style={[styles.pageTitle, { color: theme.fg }]}>Receipt</Text><Text style={[styles.sub, { color: theme.muted }]}>{subtitle}</Text></View><Card><View style={styles.paidRow}><View><Text style={[styles.receiptNumber, { color: theme.fg }]}>{title}</Text><Text style={[styles.date, { color: theme.muted }]}>{date}</Text></View><View style={[styles.status, { backgroundColor: theme.successSoft }]}><CheckCircle2 color={theme.success} size={15} /><Text style={[styles.statusText, { color: theme.success }]}>{status}</Text></View></View><View style={[styles.rule, { backgroundColor: theme.line }]} />{items.map((item, index) => <Text key={`${item}-${index}`} style={[styles.itemTitle, { color: theme.fg }]}>{item}</Text>)}<View style={[styles.total, { borderTopColor: theme.line }]}><Text style={[styles.totalLabel, { color: theme.muted }]}>Total paid</Text><Text style={[styles.totalAmount, { color: theme.fg }]}>{amount}</Text></View><Text style={[styles.reference, { color: theme.muted }]}>{reference}</Text></Card></ScrollView></SafeAreaView>; }
function money(amount: number, currency: string) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount); }
const styles = StyleSheet.create({ safe: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center', padding: spacing.lg, gap: 12 }, content: { padding: spacing.lg, gap: spacing.lg, maxWidth: 680, width: '100%', alignSelf: 'center' }, back: { width: 42, height: 42, borderWidth: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, heading: { alignItems: 'center', gap: 5 }, receiptIcon: { width: 54, height: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, pageTitle: { fontFamily: font.extraBold, fontSize: 29 }, sub: { fontFamily: font.regular, fontSize: 12, textAlign: 'center' }, paidRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, receiptNumber: { fontFamily: font.bold, fontSize: 16 }, date: { fontFamily: font.regular, fontSize: 12, marginTop: 3 }, status: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10 }, statusText: { fontFamily: font.bold, fontSize: 10 }, rule: { height: 1, marginVertical: 17 }, itemTitle: { fontFamily: font.bold, fontSize: 14, marginBottom: 8 }, total: { borderTopWidth: 1, marginTop: 14, paddingTop: 14, flexDirection: 'row', justifyContent: 'space-between' }, totalLabel: { fontFamily: font.regular, fontSize: 13 }, totalAmount: { fontFamily: font.extraBold, fontSize: 22 }, reference: { fontFamily: font.regular, fontSize: 10, marginTop: 12 } });
