import type { ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { usePathname, useRouter } from 'expo-router';
import { BarChart3, BookOpen, ClipboardList, Package, ShieldCheck, Tag } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { font, spacing } from '@/constants/theme';
import { useAppTheme } from '@/providers/app-providers';

const navigation = [
  { label: 'Overview', path: '/admin', icon: BarChart3 }, { label: 'Content', path: '/admin/content', icon: BookOpen }, { label: 'Packages', path: '/admin/packages', icon: Package }, { label: 'Coupons', path: '/admin/coupons', icon: Tag }, { label: 'Questions', path: '/admin/questions', icon: ClipboardList }, { label: 'Audit', path: '/admin/audit', icon: ShieldCheck },
] as const;

export function AdminShell({ eyebrow, title, children, action }: { eyebrow: string; title: string; children: ReactNode; action?: ReactNode }) {
  const { theme } = useAppTheme(); const router = useRouter(); const pathname = usePathname();
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.canvas }]}><View style={[styles.topbar, { backgroundColor: theme.primary }]}><View><Text style={styles.brand}>Parallax Flow</Text><Text style={styles.adminLabel}>ADMIN WORKSPACE · UI DEMO</Text></View><Pressable onPress={() => router.replace('/account')} style={styles.avatar}><Text style={styles.avatarText}>PA</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[styles.nav, { borderBottomColor: theme.line, backgroundColor: theme.surface }]}>{navigation.map((item) => { const active = pathname === item.path; const Icon = item.icon; return <Pressable key={item.path} onPress={() => router.replace(item.path as never)} style={[styles.navItem, active && { backgroundColor: theme.primarySoft }]}><Icon size={16} color={active ? theme.primary : theme.muted} /><Text style={[styles.navText, { color: active ? theme.primary : theme.muted }]}>{item.label}</Text></Pressable>; })}</ScrollView><ScrollView contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: theme.goldStrong }]}>{eyebrow}</Text><View style={styles.headingRow}><Text style={[styles.title, { color: theme.fg }]}>{title}</Text>{action}</View>{children}</ScrollView></SafeAreaView>;
}
export function AdminStat({ label, value, detail }: { label: string; value: string; detail: string }) { const { theme } = useAppTheme(); return <View style={[styles.stat, { backgroundColor: theme.surface, borderColor: theme.line }]}><Text style={[styles.statLabel, { color: theme.muted }]}>{label}</Text><Text style={[styles.statValue, { color: theme.fg }]}>{value}</Text><Text style={[styles.statDetail, { color: theme.muted }]}>{detail}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, topbar: { height: 70, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { color: '#FFFFFF', fontFamily: font.extraBold, fontSize: 19 }, adminLabel: { color: '#CDD6FF', fontFamily: font.bold, fontSize: 9, letterSpacing: 1.1, marginTop: 2 }, avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: 'rgba(255,255,255,0.14)', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFFFFF', fontFamily: font.bold, fontSize: 14 }, nav: { paddingHorizontal: 12, paddingVertical: 8, gap: 7, borderBottomWidth: 1 }, navItem: { minHeight: 34, paddingHorizontal: 10, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, navText: { fontFamily: font.semibold, fontSize: 11 }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 40, maxWidth: 850, width: '100%', alignSelf: 'center' }, eyebrow: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1.3 }, headingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontFamily: font.extraBold, fontSize: 28, letterSpacing: -0.7 }, stat: { flex: 1, minWidth: 100, borderWidth: 1, borderRadius: 14, padding: 12 }, statLabel: { fontFamily: font.bold, fontSize: 9, letterSpacing: 1 }, statValue: { fontFamily: font.extraBold, fontSize: 24, marginTop: 4 }, statDetail: { fontFamily: font.regular, fontSize: 10, marginTop: 3 } });
