import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { BookOpen, ChevronRight, FileText, Gift, ReceiptText, ShieldCheck, ShoppingBag } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { font, spacing } from '@/constants/theme';
import { getLibrary, getOrders } from '@/lib/student-content-api';
import { useAppTheme } from '@/providers/app-providers';

export function RemoteLibraryScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const [view, setView] = useState<'lessons' | 'orders'>('lessons');
  const library = useQuery({ queryKey: ['student', 'library'], queryFn: getLibrary });
  const orders = useQuery({ queryKey: ['student', 'orders'], queryFn: getOrders, enabled: view === 'orders' });
  const refetchLibrary = library.refetch;
  const refetchOrders = orders.refetch;
  useFocusEffect(useCallback(() => {
    void refetchLibrary();
    if (view === 'orders') void refetchOrders();
  }, [refetchLibrary, refetchOrders, view]));
  const loading = library.isLoading || (view === 'orders' && orders.isLoading);
  const failed = library.isError || (view === 'orders' && orders.isError);
  return <SafeAreaView edges={['top', 'left', 'right']} style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View><Text style={[styles.eyebrow, { color: theme.primary }]}>YOUR COLLECTION</Text><Text style={[styles.heading, { color: theme.fg }]}>Library</Text><Text style={[styles.subtitle, { color: theme.muted }]}>Protected learning you own, with progress and receipts in one place.</Text></View>
    <View style={[styles.hero, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.heroIcon, { backgroundColor: theme.primarySoft }]}><ShieldCheck size={23} color={theme.primary} /></View><View style={styles.heroCopy}><Text style={[styles.heroTitle, { color: theme.fg }]}>{library.data?.summary.owned ?? 0} notes ready</Text><Text style={[styles.heroHint, { color: theme.muted }]}>{library.data?.summary.expiringSoon ? `${library.data.summary.expiringSoon} access grant expires soon` : 'Your active access is synced with your account.'}</Text></View></View>
    <View style={styles.metrics}><Metric icon={<BookOpen size={17} color={theme.primary} />} value={library.data?.summary.owned ?? 0} label="Owned" /><Metric icon={<Gift size={17} color={theme.goldStrong} />} value={library.data?.summary.freePurchases ?? 0} label="Free purchases" /><Metric icon={<ShoppingBag size={17} color={theme.success} />} value={library.data?.summary.paidPurchases ?? 0} label="Paid purchases" /></View>
    <View style={[styles.switcher, { backgroundColor: theme.sunken, borderColor: theme.line }]}>{(['lessons', 'orders'] as const).map((key) => <Pressable key={key} onPress={() => setView(key)} style={[styles.switch, view === key && { backgroundColor: theme.surface, borderColor: theme.lineStrong }]}>{key === 'lessons' ? <BookOpen size={17} color={view === key ? theme.primary : theme.muted} /> : <ReceiptText size={17} color={view === key ? theme.primary : theme.muted} />}<Text style={[styles.switchText, { color: view === key ? theme.fg : theme.muted }]}>{key === 'lessons' ? 'Notes' : 'Orders'}</Text></Pressable>)}</View>
    {loading ? <View style={styles.state}><ActivityIndicator color={theme.primary} /></View> : failed ? <View style={styles.state}><Text style={[styles.hint, { color: theme.muted }]}>Unable to load your library.</Text><Pressable onPress={() => view === 'orders' ? orders.refetch() : library.refetch()}><Text style={[styles.retry, { color: theme.primary }]}>Try again</Text></Pressable></View> : view === 'lessons' ? <View style={styles.list}>{library.data?.items.map((item) => <Pressable key={item.id} onPress={() => router.push({ pathname: '/lesson/[id]', params: { id: item.id } })} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.icon, { backgroundColor: theme.primarySoft }]}><FileText size={19} color={theme.primary} /></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.title, { color: theme.fg }]}>{item.title}</Text><Text numberOfLines={1} style={[styles.hint, { color: theme.muted }]}>{item.course.name} · {item.state.progressPercent}% read · {item.state.revisionCount}× revised</Text><View style={[styles.progress, { backgroundColor: theme.sunken }]}><View style={[styles.progressFill, { backgroundColor: item.state.completed ? theme.success : theme.primary, width: `${item.state.progressPercent}%` }]} /></View></View><ChevronRight size={18} color={theme.faint} /></Pressable>)}</View> : <View style={styles.list}>{orders.data?.data.map((order) => <Pressable key={order.id} onPress={() => router.push({ pathname: '/receipt/[id]', params: { id: order.id } })} style={[styles.row, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.icon, { backgroundColor: theme.goldSoft }]}><ReceiptText size={19} color={theme.goldStrong} /></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.title, { color: theme.fg }]}>{order.orderNumber}</Text><Text style={[styles.hint, { color: theme.muted }]}>{new Date(order.createdAt).toLocaleDateString()} · {order.status}</Text></View><Text style={[styles.amount, { color: theme.fg }]}>{formatAmount(Number(order.totalAmount), order.currency)}</Text><ChevronRight size={18} color={theme.faint} /></Pressable>)}</View>}
  </ScrollView></SafeAreaView>;
}
function Metric({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { const { theme } = useAppTheme(); return <View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}>{icon}<Text style={[styles.metricValue, { color: theme.fg }]}>{value}</Text><Text numberOfLines={1} adjustsFontSizeToFit style={[styles.metricLabel, { color: theme.muted }]}>{label}</Text></View>; }
function formatAmount(amount: number, currency = 'INR') { return new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount); }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: spacing.lg, paddingBottom: 112, gap: spacing.lg }, eyebrow: { fontFamily: font.bold, fontSize: 9, letterSpacing: 1.4 }, heading: { marginTop: 3, fontFamily: font.extraBold, fontSize: 30 }, subtitle: { marginTop: 4, fontFamily: font.regular, fontSize: 12, lineHeight: 18, maxWidth: 390 }, hero: { minHeight: 104, borderWidth: 1, borderRadius: 22, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13 }, heroIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, heroCopy: { flex: 1 }, heroTitle: { fontFamily: font.bold, fontSize: 18 }, heroHint: { marginTop: 4, fontFamily: font.regular, fontSize: 10, lineHeight: 15 }, metrics: { flexDirection: 'row', gap: 8 }, metric: { flex: 1, minWidth: 0, minHeight: 91, borderWidth: 1, borderRadius: 16, padding: 12, justifyContent: 'space-between' }, metricValue: { fontFamily: font.extraBold, fontSize: 18 }, metricLabel: { fontFamily: font.medium, fontSize: 9 }, switcher: { flexDirection: 'row', padding: 4, borderWidth: 1, borderRadius: 16, gap: 4 }, switch: { flex: 1, height: 42, borderWidth: 1, borderColor: 'transparent', borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, switchText: { fontFamily: font.bold, fontSize: 11 }, list: { gap: 8 }, row: { minHeight: 76, borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, icon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, minWidth: 0 }, title: { fontFamily: font.bold, fontSize: 13 }, hint: { marginTop: 3, fontFamily: font.regular, fontSize: 9, lineHeight: 14 }, progress: { height: 4, borderRadius: 2, overflow: 'hidden', marginTop: 8 }, progressFill: { height: '100%', borderRadius: 2 }, amount: { fontFamily: font.bold, fontSize: 11 }, state: { minHeight: 160, alignItems: 'center', justifyContent: 'center', gap: 10 }, retry: { fontFamily: font.bold, fontSize: 12 } });
