import { Pressable, StyleSheet, Text, View } from 'react-native';
import { font, radius, spacing } from '@/constants/theme';
import { formatDuration } from '@/lib/demo-study';
import { useAppTheme } from '@/providers/app-providers';

export function ProgressBar({ value, color }: { value: number; color?: string }) { const { theme } = useAppTheme(); return <View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: 100, now: value }} style={[styles.progressTrack, { backgroundColor: theme.sunken }]}><View style={[styles.progressFill, { width: `${Math.max(0, Math.min(value, 100))}%`, backgroundColor: color ?? theme.primary }]} /></View>; }
export function MetricTile({ label, value, detail, tone = 'primary' }: { label: string; value: string | number; detail: string; tone?: 'primary' | 'gold' | 'success' }) { const { theme } = useAppTheme(); const color = tone === 'gold' ? theme.gold : tone === 'success' ? theme.success : theme.primary; return <View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><Text style={[styles.metricLabel, { color }]}>{label}</Text><Text style={[styles.metricValue, { color: theme.fg }]}>{value}</Text><Text style={[styles.metricDetail, { color: theme.muted }]}>{detail}</Text></View>; }
export function SessionButton({ active, seconds, onPress, size = 'compact' }: { active: boolean; seconds: number; onPress: () => void; size?: 'compact' | 'large' }) { const { theme } = useAppTheme(); const large = size === 'large'; return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.sessionButton, large ? styles.sessionLarge : styles.sessionCompact, { borderColor: active ? theme.gold : theme.primary, backgroundColor: active ? theme.goldSoft : theme.primarySoft }, pressed && { opacity: 0.84 }]}><Text style={[styles.sessionTop, { color: active ? theme.goldStrong : theme.primary }]}>{active ? 'SESSION LIVE' : 'CHECK IN'}</Text><Text style={[styles.sessionTime, { color: theme.fg }]}>{active ? formatDuration(seconds) : 'START'}</Text><Text style={[styles.sessionBottom, { color: theme.muted }]}>{active ? 'Tap to check out' : 'Focus with intent'}</Text></Pressable>; }
const styles = StyleSheet.create({ progressTrack: { height: 8, borderRadius: radius.pill, overflow: 'hidden' }, progressFill: { height: '100%', borderRadius: radius.pill }, metric: { flex: 1, minWidth: 108, borderWidth: 1, borderRadius: radius.card, padding: spacing.md, gap: 3 }, metricLabel: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1 }, metricValue: { fontFamily: font.extraBold, fontSize: 24, letterSpacing: -0.5 }, metricDetail: { fontFamily: font.regular, fontSize: 11, lineHeight: 16 }, sessionButton: { alignItems: 'center', justifyContent: 'center', borderWidth: 9, borderRadius: 999 }, sessionCompact: { width: 116, height: 116 }, sessionLarge: { width: 174, height: 174, alignSelf: 'center' }, sessionTop: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1 }, sessionTime: { marginTop: 4, fontFamily: font.extraBold, fontSize: 18 }, sessionBottom: { marginTop: 3, fontFamily: font.medium, fontSize: 10 } });
