import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Eye, Moon } from 'lucide-react-native';
import { font } from '@/constants/theme';
import { useAppTheme } from '@/providers/app-providers';

export function StudentHeader() {
  const { theme, preference, setPreference } = useAppTheme(); const router = useRouter(); const dark = theme.canvas === '#0D1226';
  return <LinearGradient colors={dark ? ['#0B1024', '#121A39'] : ['#FFFFFF', '#F6F7FC']} style={[styles.header, { borderBottomColor: dark ? '#28345C' : theme.line }]}><View style={styles.brand}><View style={[styles.brandMark, { backgroundColor: dark ? '#202A59' : theme.primarySoft }]}><Eye size={22} strokeWidth={2.5} color={theme.primary} /></View><Text numberOfLines={1} adjustsFontSizeToFit style={[styles.wordmark, { color: dark ? '#AEBBFF' : theme.primaryStrong }]}>Parallax Flow</Text></View><View style={styles.actions}><Pressable accessibilityLabel="Toggle theme" onPress={() => setPreference(preference === 'dark' ? 'light' : 'dark')} style={[styles.themeButton, { borderColor: dark ? '#7181DC' : theme.primary, backgroundColor: dark ? '#151D40' : theme.surface }]}><Moon size={23} color={dark ? '#C9D0FF' : theme.muted} strokeWidth={2.2} /></Pressable><Pressable accessibilityLabel="Account" onPress={() => router.push('/account')} style={[styles.avatar, { backgroundColor: dark ? '#293666' : theme.primarySoft }]}><Text style={[styles.avatarText, { color: dark ? '#AEBBFF' : theme.primaryStrong }]}>PA</Text></Pressable></View></LinearGradient>;
}
const styles = StyleSheet.create({ header: { height: 64, borderBottomWidth: 1, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#10162F', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 3 }, brand: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8, paddingRight: 7 }, brandMark: { height: 31, width: 31, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, wordmark: { flexShrink: 1, fontFamily: font.extraBold, fontSize: 19, letterSpacing: -0.55 }, actions: { flexDirection: 'row', gap: 8, alignItems: 'center' }, themeButton: { height: 46, width: 46, borderRadius: 15, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, avatar: { height: 43, width: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: font.bold, fontSize: 15 } });
