import { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { BarChart3, CalendarDays, CheckCircle2, CircleDollarSign, Percent, Plus, Search, Tag, TicketPercent, X, Zap } from 'lucide-react-native';

import { AdminShell } from '@/components/admin-shell';
import { font, radius, spacing } from '@/constants/theme';
import { adminCoupons } from '@/lib/demo-admin';
import { useAppTheme } from '@/providers/app-providers';

type CouponStatus = 'Active' | 'Disabled';
type CouponKind = 'Percentage' | 'Flat';
type CouponItem = { id: string; code: string; kind: CouponKind; value: number; status: CouponStatus; redemptions: number; expiresOn: string; scope: string; minimumOrder: number; usageLimit: number };
const initialCoupons: CouponItem[] = adminCoupons.map((coupon) => ({ ...coupon, kind: coupon.kind as CouponKind, scope: coupon.code === 'POLITY50' ? 'JEE · Mains' : 'All courses', minimumOrder: coupon.kind === 'Flat' ? 299 : 499, usageLimit: coupon.code === 'POLITY50' ? 50 : 200 }));

export default function AdminCoupons() {
  const { theme } = useAppTheme();
  const [coupons, setCoupons] = useState(initialCoupons);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'All' | CouponStatus>('All');
  const [showCreate, setShowCreate] = useState(false);
  const [createdCode, setCreatedCode] = useState<string | null>(null);
  const visibleCoupons = useMemo(() => coupons.filter((coupon) => (filter === 'All' || coupon.status === filter) && (!query.trim() || `${coupon.code} ${coupon.scope}`.toLowerCase().includes(query.trim().toLowerCase()))), [coupons, filter, query]);
  const activeCoupons = coupons.filter((coupon) => coupon.status === 'Active');
  const totalRedemptions = coupons.reduce((total, coupon) => total + coupon.redemptions, 0);
  const addAction = <Pressable accessibilityRole="button" accessibilityLabel="Create coupon" onPress={() => setShowCreate(true)} style={({ pressed }) => [styles.add, { backgroundColor: theme.primary }, pressed && styles.pressed]}><Plus color={theme.primaryFg} size={16} /><Text style={[styles.addText, { color: theme.primaryFg }]}>New</Text></Pressable>;

  const createCoupon = (coupon: Omit<CouponItem, 'id' | 'redemptions'>) => {
    setCoupons((current) => [{ ...coupon, id: `CP-${String(current.length + 1).padStart(2, '0')}`, redemptions: 0 }, ...current]);
    setCreatedCode(coupon.code);
    setShowCreate(false);
  };

  return <>
    <AdminShell eyebrow="COMMERCE" title="Coupons" description="Create focused offers and keep every promotion easy to review." action={addAction}>
      <View style={[styles.hero, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.heroIcon, { backgroundColor: theme.goldSoft }]}><TicketPercent size={23} color={theme.goldStrong} /></View><View style={styles.flex}><Text style={[styles.heroEyebrow, { color: theme.goldStrong }]}>ACTIVE OFFERS</Text><Text style={[styles.heroValue, { color: theme.fg }]}>{activeCoupons.length}</Text><Text style={[styles.heroHint, { color: theme.muted }]}>{totalRedemptions} total redemptions across mobile coupons</Text></View><View style={[styles.livePill, { backgroundColor: theme.successSoft }]}><Zap size={12} color={theme.success} /><Text style={[styles.liveText, { color: theme.success }]}>LIVE</Text></View></View>

      <View style={styles.metrics}><View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.metricIcon, { backgroundColor: theme.primarySoft }]}><BarChart3 size={17} color={theme.primaryStrong} /></View><Text style={[styles.metricValue, { color: theme.fg }]}>{totalRedemptions}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>Redemptions</Text></View><View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.metricIcon, { backgroundColor: theme.successSoft }]}><Tag size={17} color={theme.success} /></View><Text style={[styles.metricValue, { color: theme.fg }]}>{coupons.length}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>Total coupons</Text></View></View>

      {createdCode ? <View style={[styles.createdBanner, { backgroundColor: theme.successSoft, borderColor: theme.line }]}><CheckCircle2 size={18} color={theme.success} /><View style={styles.flex}><Text style={[styles.createdTitle, { color: theme.success }]}>Coupon created</Text><Text style={[styles.createdCopy, { color: theme.muted }]}>{createdCode} is now visible in this UI demo.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Dismiss" onPress={() => setCreatedCode(null)}><X size={16} color={theme.muted} /></Pressable></View> : null}

      <View style={[styles.searchPanel, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={styles.searchRow}><Search size={17} color={theme.faint} /><TextInput value={query} onChangeText={setQuery} placeholder="Search coupon or course" placeholderTextColor={theme.faint} style={[styles.searchInput, { color: theme.fg }]} />{query ? <Pressable onPress={() => setQuery('')}><Text style={[styles.clearText, { color: theme.primaryStrong }]}>Clear</Text></Pressable> : null}</View><View style={[styles.searchRule, { backgroundColor: theme.line }]} /><View style={styles.filters}>{(['All', 'Active', 'Disabled'] as const).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, { backgroundColor: filter === item ? theme.primarySoft : theme.sunken, borderColor: filter === item ? theme.primary : 'transparent' }]}><Text style={[styles.filterText, { color: filter === item ? theme.primaryStrong : theme.muted }]}>{item}</Text></Pressable>)}</View></View>

      <View style={styles.sectionHeading}><View><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>PROMOTIONS</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>Coupon library</Text></View><Text style={[styles.resultCount, { color: theme.muted }]}>{visibleCoupons.length} shown</Text></View>
      <View style={styles.list}>{visibleCoupons.map((coupon) => { const active = coupon.status === 'Active'; return <View key={coupon.id} style={[styles.couponCard, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.couponAccent, { backgroundColor: active ? theme.gold : theme.lineStrong }]} /><View style={styles.couponTop}><View style={[styles.couponIcon, { backgroundColor: active ? theme.goldSoft : theme.sunken }]}>{coupon.kind === 'Percentage' ? <Percent size={18} color={active ? theme.goldStrong : theme.faint} /> : <CircleDollarSign size={18} color={active ? theme.goldStrong : theme.faint} />}</View><View style={styles.flex}><Text style={[styles.couponCode, { color: theme.fg }]}>{coupon.code}</Text><Text style={[styles.couponOffer, { color: theme.muted }]}>{coupon.kind === 'Percentage' ? `${coupon.value}% off` : `₹${coupon.value} off`} · Min. ₹{coupon.minimumOrder}</Text></View><View style={[styles.statusPill, { backgroundColor: active ? theme.successSoft : theme.sunken }]}><View style={[styles.statusDot, { backgroundColor: active ? theme.success : theme.faint }]} /><Text style={[styles.statusText, { color: active ? theme.success : theme.muted }]}>{coupon.status.toUpperCase()}</Text></View></View><View style={[styles.couponDetails, { borderTopColor: theme.line }]}><CouponFact icon={Tag} label="Scope" value={coupon.scope} /><CouponFact icon={CalendarDays} label="Expires" value={coupon.expiresOn} /><CouponFact icon={BarChart3} label="Used" value={`${coupon.redemptions}/${coupon.usageLimit}`} /></View></View>; })}</View>
      {!visibleCoupons.length ? <View style={[styles.empty, { backgroundColor: theme.surface, borderColor: theme.line }]}><TicketPercent size={22} color={theme.faint} /><Text style={[styles.emptyTitle, { color: theme.fg }]}>No matching coupons</Text><Text style={[styles.emptyCopy, { color: theme.muted }]}>Change the search or status filter.</Text></View> : null}
    </AdminShell>
    <CouponModal visible={showCreate} existingCodes={coupons.map((coupon) => coupon.code)} onClose={() => setShowCreate(false)} onCreate={createCoupon} />
  </>;
}

function CouponFact({ icon: Icon, label, value }: { icon: typeof Tag; label: string; value: string }) { const { theme } = useAppTheme(); return <View style={styles.fact}><Icon size={13} color={theme.faint} /><View style={styles.factCopy}><Text style={[styles.factLabel, { color: theme.faint }]}>{label}</Text><Text numberOfLines={1} style={[styles.factValue, { color: theme.muted }]}>{value}</Text></View></View>; }

function CouponModal({ visible, existingCodes, onClose, onCreate }: { visible: boolean; existingCodes: string[]; onClose: () => void; onCreate: (coupon: Omit<CouponItem, 'id' | 'redemptions'>) => void }) {
  const { theme } = useAppTheme();
  const [code, setCode] = useState('');
  const [kind, setKind] = useState<CouponKind>('Percentage');
  const [value, setValue] = useState('10');
  const [scope, setScope] = useState('All courses');
  const [minimumOrder, setMinimumOrder] = useState('499');
  const [expiresOn, setExpiresOn] = useState('31 Aug 2026');
  const [usageLimit, setUsageLimit] = useState('100');
  const [active, setActive] = useState(true);
  const normalizedCode = code.trim().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 16);
  const duplicate = existingCodes.includes(normalizedCode);
  const valid = normalizedCode.length >= 4 && !duplicate && Number(value) > 0 && Number(minimumOrder) >= 0 && Number(usageLimit) > 0 && expiresOn.trim().length >= 6;
  const close = () => { setCode(''); onClose(); };
  const submit = () => { if (!valid) return; onCreate({ code: normalizedCode, kind, value: Number(value), status: active ? 'Active' : 'Disabled', expiresOn: expiresOn.trim(), scope, minimumOrder: Number(minimumOrder), usageLimit: Number(usageLimit) }); setCode(''); };

  return <Modal visible={visible} transparent animationType="none" onRequestClose={close}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.modalRoot}><View style={styles.modalRoot}><Pressable accessibilityRole="button" accessibilityLabel="Close coupon creator" onPress={close} style={styles.backdrop} /><View style={[styles.sheet, { backgroundColor: theme.elevated, borderColor: theme.lineStrong }]}><View style={[styles.sheetHandle, { backgroundColor: theme.lineStrong }]} /><View style={styles.sheetHeader}><View style={[styles.sheetIcon, { backgroundColor: theme.goldSoft }]}><TicketPercent size={19} color={theme.goldStrong} /></View><View style={styles.flex}><Text style={[styles.sheetEyebrow, { color: theme.goldStrong }]}>NEW MOBILE COUPON</Text><Text style={[styles.sheetTitle, { color: theme.fg }]}>Create an offer</Text><Text style={[styles.sheetCopy, { color: theme.muted }]}>Set the promotion details and preview how it will appear.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={close} style={[styles.close, { backgroundColor: theme.sunken }]}><X size={18} color={theme.muted} /></Pressable></View>
        <ScrollView style={styles.formScroll} contentContainerStyle={styles.formContent} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
          <Field label="Coupon code"><TextInput autoCapitalize="characters" value={code} onChangeText={setCode} placeholder="Example: JEE20" placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: duplicate ? theme.danger : theme.line, color: theme.fg }]} />{duplicate ? <Text style={[styles.fieldError, { color: theme.danger }]}>This code already exists.</Text> : null}</Field>
          <Field label="Discount type"><View style={[styles.segment, { backgroundColor: theme.sunken }]}>{(['Percentage', 'Flat'] as const).map((item) => <Pressable key={item} onPress={() => setKind(item)} style={[styles.segmentItem, kind === item && { backgroundColor: theme.surface }]}>{item === 'Percentage' ? <Percent size={15} color={kind === item ? theme.primaryStrong : theme.muted} /> : <CircleDollarSign size={15} color={kind === item ? theme.primaryStrong : theme.muted} />}<Text style={[styles.segmentText, { color: kind === item ? theme.fg : theme.muted }]}>{item}</Text></Pressable>)}</View></Field>
          <View style={styles.fieldRow}><View style={styles.fieldHalf}><Field label={kind === 'Percentage' ? 'Discount %' : 'Flat amount'}><TextInput value={value} onChangeText={(text) => setValue(text.replace(/\D/g, '').slice(0, 5))} keyboardType="number-pad" placeholder="10" placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /></Field></View><View style={styles.fieldHalf}><Field label="Minimum order"><TextInput value={minimumOrder} onChangeText={(text) => setMinimumOrder(text.replace(/\D/g, '').slice(0, 6))} keyboardType="number-pad" placeholder="499" placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /></Field></View></View>
          <Field label="Applicable course"><View style={styles.scopeGrid}>{['All courses', 'JEE', 'CA', 'NEET'].map((item) => <Pressable key={item} onPress={() => setScope(item)} style={[styles.scopeOption, { backgroundColor: scope === item ? theme.primarySoft : theme.sunken, borderColor: scope === item ? theme.primary : 'transparent' }]}><Text style={[styles.scopeText, { color: scope === item ? theme.primaryStrong : theme.muted }]}>{item}</Text></Pressable>)}</View></Field>
          <View style={styles.fieldRow}><View style={styles.fieldHalf}><Field label="Expiry"><TextInput value={expiresOn} onChangeText={setExpiresOn} placeholder="31 Aug 2026" placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /></Field></View><View style={styles.fieldHalf}><Field label="Usage limit"><TextInput value={usageLimit} onChangeText={(text) => setUsageLimit(text.replace(/\D/g, '').slice(0, 6))} keyboardType="number-pad" placeholder="100" placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /></Field></View></View>
          <View style={[styles.statusControl, { backgroundColor: theme.sunken, borderColor: theme.line }]}><View style={styles.flex}><Text style={[styles.statusControlTitle, { color: theme.fg }]}>Activate immediately</Text><Text style={[styles.statusControlCopy, { color: theme.muted }]}>The coupon appears as active after creation.</Text></View><Pressable accessibilityRole="switch" accessibilityState={{ checked: active }} onPress={() => setActive((current) => !current)} style={[styles.toggle, { backgroundColor: active ? theme.primary : theme.surface, borderColor: active ? theme.primary : theme.line, justifyContent: active ? 'flex-end' : 'flex-start' }]}><View style={[styles.toggleKnob, { backgroundColor: active ? theme.primaryFg : theme.faint }]} /></Pressable></View>
          <View style={[styles.previewCard, { backgroundColor: theme.goldSoft, borderColor: theme.line }]}><View style={styles.flex}><Text style={[styles.previewEyebrow, { color: theme.goldStrong }]}>COUPON PREVIEW</Text><Text style={[styles.previewCode, { color: theme.fg }]}>{normalizedCode || 'YOURCODE'}</Text><Text style={[styles.previewOffer, { color: theme.muted }]}>{kind === 'Percentage' ? `${value || '0'}% off` : `₹${value || '0'} off`} · {scope}</Text></View><TicketPercent size={26} color={theme.goldStrong} /></View>
        </ScrollView>
        <Pressable disabled={!valid} onPress={submit} style={({ pressed }) => [styles.submit, { backgroundColor: theme.primary }, !valid && styles.disabled, pressed && styles.pressed]}><Plus size={16} color={theme.primaryFg} /><Text style={[styles.submitText, { color: theme.primaryFg }]}>Create coupon</Text></Pressable>
      </View></View></KeyboardAvoidingView></Modal>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { const { theme } = useAppTheme(); return <View><Text style={[styles.fieldLabel, { color: theme.muted }]}>{label}</Text>{children}</View>; }

const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 }, add: { minHeight: 37, paddingHorizontal: 10, borderRadius: 11, flexDirection: 'row', alignItems: 'center', gap: 4 }, addText: { fontFamily: font.bold, fontSize: 9 }, pressed: { opacity: .74, transform: [{ scale: .98 }] },
  hero: { minHeight: 116, borderWidth: 1, borderRadius: 19, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11 }, heroIcon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, heroEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.05 }, heroValue: { marginTop: 2, fontFamily: font.extraBold, fontSize: 27, lineHeight: 33 }, heroHint: { fontFamily: font.regular, fontSize: 8 }, livePill: { minHeight: 27, borderRadius: radius.pill, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 }, liveText: { fontFamily: font.bold, fontSize: 7, letterSpacing: .6 },
  metrics: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, minWidth: 0, minHeight: 88, borderWidth: 1, borderRadius: 16, padding: 11 }, metricIcon: { width: 31, height: 31, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, metricValue: { marginTop: 7, fontFamily: font.extraBold, fontSize: 16 }, metricLabel: { marginTop: 2, fontFamily: font.regular, fontSize: 8 }, createdBanner: { minHeight: 65, borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9 }, createdTitle: { fontFamily: font.bold, fontSize: 10 }, createdCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8 },
  searchPanel: { borderWidth: 1, borderRadius: 16, padding: 10 }, searchRow: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchInput: { flex: 1, minWidth: 0, paddingVertical: 0, fontFamily: font.regular, fontSize: 11 }, clearText: { fontFamily: font.bold, fontSize: 8 }, searchRule: { height: 1, marginVertical: 8 }, filters: { flexDirection: 'row', gap: 6 }, filter: { flex: 1, minHeight: 30, borderWidth: 1, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center' }, filterText: { fontFamily: font.bold, fontSize: 7 }, sectionHeading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, sectionEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.05 }, sectionTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 17 }, resultCount: { fontFamily: font.semibold, fontSize: 8 }, list: { gap: spacing.sm },
  couponCard: { position: 'relative', minHeight: 128, overflow: 'hidden', borderWidth: 1, borderRadius: 17, padding: 11 }, couponAccent: { position: 'absolute', left: 0, top: 15, bottom: 15, width: 3, borderTopRightRadius: 3, borderBottomRightRadius: 3 }, couponTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, couponIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, couponCode: { fontFamily: font.extraBold, fontSize: 12, letterSpacing: .5 }, couponOffer: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, statusPill: { minHeight: 24, borderRadius: radius.pill, paddingHorizontal: 7, flexDirection: 'row', alignItems: 'center', gap: 4 }, statusDot: { width: 5, height: 5, borderRadius: 3 }, statusText: { fontFamily: font.bold, fontSize: 6, letterSpacing: .5 }, couponDetails: { minHeight: 50, marginTop: 10, paddingTop: 9, borderTopWidth: 1, flexDirection: 'row', gap: 7 }, fact: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 5 }, factCopy: { flex: 1, minWidth: 0 }, factLabel: { fontFamily: font.regular, fontSize: 6 }, factValue: { marginTop: 2, fontFamily: font.semibold, fontSize: 7 }, empty: { minHeight: 145, borderWidth: 1, borderRadius: 17, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { marginTop: 8, fontFamily: font.bold, fontSize: 12 }, emptyCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, backdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(0,0,0,.72)' }, sheet: { width: '100%', maxWidth: 680, maxHeight: '92%', alignSelf: 'center', borderWidth: 1, borderBottomWidth: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing.lg, paddingBottom: 24 }, sheetHandle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 13 }, sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, sheetIcon: { width: 39, height: 39, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, sheetEyebrow: { fontFamily: font.bold, fontSize: 7, letterSpacing: 1 }, sheetTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 18 }, sheetCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, close: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, formScroll: { marginTop: 13 }, formContent: { gap: 12, paddingBottom: 3 }, fieldLabel: { marginBottom: 6, fontFamily: font.bold, fontSize: 8, letterSpacing: .55 }, input: { minHeight: 44, borderWidth: 1, borderRadius: 11, paddingHorizontal: 10, paddingVertical: 0, fontFamily: font.regular, fontSize: 11 }, fieldError: { marginTop: 4, fontFamily: font.semibold, fontSize: 7 }, fieldRow: { flexDirection: 'row', gap: 8 }, fieldHalf: { flex: 1, minWidth: 0 }, segment: { flexDirection: 'row', borderRadius: 12, padding: 4, gap: 4 }, segmentItem: { flex: 1, minHeight: 36, borderRadius: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, segmentText: { fontFamily: font.bold, fontSize: 8 }, scopeGrid: { flexDirection: 'row', gap: 5 }, scopeOption: { flex: 1, minHeight: 32, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, scopeText: { fontFamily: font.bold, fontSize: 7 }, statusControl: { minHeight: 60, borderWidth: 1, borderRadius: 13, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 9 }, statusControlTitle: { fontFamily: font.bold, fontSize: 9 }, statusControlCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 7 }, toggle: { width: 43, height: 26, borderRadius: radius.pill, borderWidth: 1, padding: 3, flexDirection: 'row', alignItems: 'center' }, toggleKnob: { width: 18, height: 18, borderRadius: 9 }, previewCard: { minHeight: 76, borderWidth: 1, borderRadius: 14, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 8 }, previewEyebrow: { fontFamily: font.bold, fontSize: 6, letterSpacing: .8 }, previewCode: { marginTop: 3, fontFamily: font.extraBold, fontSize: 13, letterSpacing: .4 }, previewOffer: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, submit: { minHeight: 45, marginTop: 13, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, submitText: { fontFamily: font.bold, fontSize: 10 }, disabled: { opacity: .42 },
});
