import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BookOpen, CheckCircle2, ChevronDown, CircleHelp, FileQuestion, LockKeyhole, PenLine } from 'lucide-react-native';

import { AdminShell } from '@/components/admin-shell';
import { font, radius, spacing } from '@/constants/theme';
import { practiceSubjects } from '@/lib/demo-practice';
import { useAppTheme } from '@/providers/app-providers';

export default function AdminQuestions() {
  const { theme } = useAppTheme();
  const [expandedSubjectId, setExpandedSubjectId] = useState(practiceSubjects[0]?.id ?? '');
  const topicCount = practiceSubjects.reduce((total, subject) => total + subject.topics.length, 0);
  const questionCount = practiceSubjects.reduce((total, subject) => total + subject.topics.reduce((sum, topic) => sum + topic.questions.length, 0), 0);

  return <AdminShell eyebrow="ASSESSMENT" title="Question bank" description="Review the subject and topic coverage available in Student Practice.">
    <View style={[styles.hero, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.heroIcon, { backgroundColor: theme.primarySoft }]}><FileQuestion size={23} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.heroEyebrow, { color: theme.primary }]}>PRACTICE COVERAGE</Text><Text style={[styles.heroValue, { color: theme.fg }]}>{questionCount} questions</Text><Text style={[styles.heroHint, { color: theme.muted }]}>{practiceSubjects.length} subjects · {topicCount} topics · MCQ and written</Text></View><View style={[styles.readOnly, { backgroundColor: theme.primarySoft }]}><LockKeyhole size={12} color={theme.primaryStrong} /><Text style={[styles.readOnlyText, { color: theme.primaryStrong }]}>READ ONLY</Text></View></View>

    <View style={styles.metrics}><Metric icon={BookOpen} value={String(practiceSubjects.length)} label="Subjects" color={theme.primaryStrong} soft={theme.primarySoft} /><Metric icon={CircleHelp} value={String(questionCount)} label="MCQs" color={theme.goldStrong} soft={theme.goldSoft} /><Metric icon={PenLine} value={String(topicCount)} label="Written" color={theme.success} soft={theme.successSoft} /></View>

    <View><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>SUBJECT COVERAGE</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>Practice structure</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>Expand a subject to review its available topics</Text></View>
    <View style={styles.subjectList}>{practiceSubjects.map((subject) => { const expanded = expandedSubjectId === subject.id; const subjectQuestions = subject.topics.reduce((total, topic) => total + topic.questions.length, 0); return <View key={subject.id} style={[styles.subjectCard, { backgroundColor: theme.surface, borderColor: expanded ? theme.lineStrong : theme.line }]}><Pressable accessibilityRole="button" accessibilityState={{ expanded }} onPress={() => setExpandedSubjectId(expanded ? '' : subject.id)} style={({ pressed }) => [styles.subjectHeader, pressed && styles.pressed]}><View style={[styles.subjectIcon, { backgroundColor: theme.primarySoft }]}><BookOpen size={18} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.subjectTitle, { color: theme.fg }]}>{subject.title}</Text><Text style={[styles.subjectMeta, { color: theme.muted }]}>{subject.topics.length} topics · {subjectQuestions} questions</Text></View><ChevronDown size={17} color={theme.muted} style={{ transform: [{ rotate: expanded ? '180deg' : '0deg' }] }} /></Pressable>{expanded ? <View style={[styles.topicList, { borderTopColor: theme.line }]}>{subject.topics.map((topic) => <View key={topic.id} style={styles.topicRow}><View style={[styles.topicIndex, { backgroundColor: theme.sunken }]}><CircleHelp size={14} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.topicTitle, { color: theme.fg }]}>{topic.title}</Text><Text style={[styles.topicMeta, { color: theme.muted }]}>{topic.questions.length} MCQs · 1 written prompt</Text></View><CheckCircle2 size={14} color={theme.success} /></View>)}</View> : null}</View>; })}</View>

    <View style={[styles.notice, { backgroundColor: theme.primarySoft, borderColor: theme.line }]}><LockKeyhole size={17} color={theme.primaryStrong} /><View style={styles.flex}><Text style={[styles.noticeTitle, { color: theme.primaryStrong }]}>Website-managed questions</Text><Text style={[styles.noticeCopy, { color: theme.muted }]}>Creating, editing and publishing questions are intentionally not available in the mobile Admin.</Text></View></View>
  </AdminShell>;
}

function Metric({ icon: Icon, value, label, color, soft }: { icon: typeof BookOpen; value: string; label: string; color: string; soft: string }) { const { theme } = useAppTheme(); return <View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.metricIcon, { backgroundColor: soft }]}><Icon size={16} color={color} /></View><Text style={[styles.metricValue, { color: theme.fg }]}>{value}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 }, hero: { minHeight: 116, borderWidth: 1, borderRadius: 19, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, heroIcon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, heroEyebrow: { fontFamily: font.bold, fontSize: 7, letterSpacing: 1.05 }, heroValue: { marginTop: 3, fontFamily: font.extraBold, fontSize: 20 }, heroHint: { marginTop: 2, fontFamily: font.regular, fontSize: 8 }, readOnly: { minHeight: 26, borderRadius: radius.pill, paddingHorizontal: 7, flexDirection: 'row', alignItems: 'center', gap: 4 }, readOnlyText: { fontFamily: font.bold, fontSize: 6, letterSpacing: .5 },
  metrics: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, minWidth: 0, minHeight: 88, borderWidth: 1, borderRadius: 16, padding: 10 }, metricIcon: { width: 29, height: 29, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, metricValue: { marginTop: 6, fontFamily: font.extraBold, fontSize: 15 }, metricLabel: { marginTop: 2, fontFamily: font.regular, fontSize: 7 }, sectionEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.05 }, sectionTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 17 }, sectionHint: { marginTop: 3, fontFamily: font.regular, fontSize: 8 },
  subjectList: { gap: spacing.sm }, subjectCard: { overflow: 'hidden', borderWidth: 1, borderRadius: 16 }, subjectHeader: { minHeight: 69, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 9 }, subjectIcon: { width: 39, height: 39, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, subjectTitle: { fontFamily: font.bold, fontSize: 11 }, subjectMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, topicList: { borderTopWidth: 1, paddingHorizontal: 10, paddingBottom: 4 }, topicRow: { minHeight: 55, flexDirection: 'row', alignItems: 'center', gap: 8 }, topicIndex: { width: 31, height: 31, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, topicTitle: { fontFamily: font.semibold, fontSize: 9 }, topicMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 7 }, notice: { minHeight: 72, borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9 }, noticeTitle: { fontFamily: font.bold, fontSize: 10 }, noticeCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8, lineHeight: 13 }, pressed: { opacity: .74 },
});
