import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { BookOpen, ChevronRight, FileText, ReceiptText } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProgressBar } from '@/components/study-ui';
import { Card } from '@/components/ui';
import { font, spacing } from '@/constants/theme';
import { orders, ownedLessons } from '@/lib/demo-commerce';
import { useAppTheme } from '@/providers/app-providers';

export default function LibraryScreen() { const { theme } = useAppTheme(); const router = useRouter(); return <SafeAreaView edges={['left', 'right']} style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={[styles.eyebrow, { color: theme.goldStrong }]}>YOUR ACCESS</Text><Text style={[styles.title, { color: theme.fg }]}>My Library</Text><Text style={[styles.description, { color: theme.muted }]}>Your owned lessons and permanent purchase records.</Text><Card style={{ ...styles.hero, backgroundColor: theme.primary }}><View style={styles.heroIcon}><BookOpen color="#D8BC86" size={25} /></View><View><Text style={styles.heroCount}>{ownedLessons.length}</Text><Text style={styles.heroLabel}>owned lessons · yours forever</Text></View></Card><Text style={[styles.sectionTitle, { color: theme.fg }]}>Owned lessons</Text><View style={styles.list}>{ownedLessons.map((lesson) => <Pressable key={lesson.id} onPress={() => router.push({ pathname: '/lesson/[id]', params: { id: lesson.id } })} style={({ pressed }) => [styles.lesson, { backgroundColor: theme.surface, borderColor: theme.line }, pressed && { opacity: 0.86 }]}><View style={[styles.lessonIcon, { backgroundColor: theme.primarySoft }]}><FileText size={19} color={theme.primary} /></View><View style={styles.lessonCopy}><Text style={[styles.lessonTitle, { color: theme.fg }]}>{lesson.title}</Text><Text style={[styles.lessonDetail, { color: theme.muted }]}>{lesson.subject} · {lesson.pages} pages · {lesson.revised}× revised</Text><View style={styles.progress}><ProgressBar value={lesson.progress} /></View></View><ChevronRight size={19} color={theme.faint} /></Pressable>)}</View><View style={styles.orderHeading}><Text style={[styles.sectionTitle, { color: theme.fg }]}>Order history</Text><Text style={[styles.orderCount, { color: theme.muted }]}>{orders.length} orders</Text></View><View style={styles.list}>{orders.map((order) => <Pressable key={order.id} onPress={() => router.push({ pathname: '/receipt/[id]', params: { id: order.id } })} style={({ pressed }) => [styles.order, { backgroundColor: theme.surface, borderColor: theme.line }, pressed && { opacity: 0.86 }]}><View style={[styles.lessonIcon, { backgroundColor: theme.goldSoft }]}><ReceiptText size={19} color={theme.goldStrong} /></View><View style={styles.lessonCopy}><Text style={[styles.lessonTitle, { color: theme.fg }]}>{order.items}</Text><Text style={[styles.lessonDetail, { color: theme.muted }]}>{order.id} · {order.date}</Text></View><View style={styles.amount}><Text style={[styles.amountValue, { color: theme.fg }]}>{order.amount}</Text><Text style={[styles.paid, { color: theme.success }]}>{order.status}</Text></View></Pressable>)}</View></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 86, maxWidth: 680, width: '100%', alignSelf: 'center' }, eyebrow: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1.4 }, title: { fontFamily: font.extraBold, fontSize: 30, letterSpacing: -0.8 }, description: { fontFamily: font.regular, fontSize: 14, marginTop: -5 }, hero: { borderWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 13 }, heroIcon: { width: 48, height: 48, borderRadius: 15, backgroundColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' }, heroCount: { color: '#FFFFFF', fontFamily: font.extraBold, fontSize: 27 }, heroLabel: { color: '#D6DDFE', fontFamily: font.regular, fontSize: 12 }, sectionTitle: { fontFamily: font.bold, fontSize: 17 }, list: { gap: spacing.sm }, lesson: { minHeight: 80, borderWidth: 1, borderRadius: 15, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, order: { minHeight: 72, borderWidth: 1, borderRadius: 15, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, lessonIcon: { width: 39, height: 39, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, lessonCopy: { flex: 1, minWidth: 0 }, lessonTitle: { fontFamily: font.bold, fontSize: 13 }, lessonDetail: { fontFamily: font.regular, fontSize: 10, marginTop: 3 }, progress: { marginTop: 7 }, orderHeading: { marginTop: 4, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' }, orderCount: { fontFamily: font.regular, fontSize: 11 }, amount: { alignItems: 'flex-end' }, amountValue: { fontFamily: font.bold, fontSize: 13 }, paid: { fontFamily: font.bold, fontSize: 10, marginTop: 3 } });
