import { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { BookOpen, CheckCircle2, CircleHelp, Clock3, Flag, Layers3, PenLine, Play, RotateCcw } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppButton, Card } from '@/components/ui';
import { font, radius, spacing } from '@/constants/theme';
import { practiceSubjects } from '@/lib/demo-practice';
import { useAppTheme } from '@/providers/app-providers';

type PracticeMode = 'mcq' | 'written';

export default function PracticeScreen() {
  const { theme } = useAppTheme();
  const [mode, setMode] = useState<PracticeMode>('mcq');
  const [subjectId, setSubjectId] = useState(practiceSubjects[0].id);
  const subject = practiceSubjects.find((item) => item.id === subjectId) ?? practiceSubjects[0];
  const [topicId, setTopicId] = useState(subject.topics[0].id);
  const topic = subject.topics.find((item) => item.id === topicId) ?? subject.topics[0];
  const questions = topic.questions;
  const [started, setStarted] = useState(false);
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [marked, setMarked] = useState<Set<string>>(new Set());
  const [submitted, setSubmitted] = useState<Set<string>>(new Set());
  const [timerMinutes, setTimerMinutes] = useState<number | null>(10);
  const [timeLeft, setTimeLeft] = useState(10 * 60);
  const [written, setWritten] = useState('');
  const [writtenSubmitted, setWrittenSubmitted] = useState(false);
  const question = questions[Math.min(current, questions.length - 1)];
  const selected = answers[question.id];
  const isSubmitted = submitted.has(question.id);
  const answeredCount = questions.filter((item) => Boolean(answers[item.id])).length;
  const progress = Math.round((answeredCount / Math.max(questions.length, 1)) * 100);

  useEffect(() => {
    if (!started || mode !== 'mcq' || timerMinutes === null || timeLeft <= 0) return;
    const interval = setInterval(() => setTimeLeft((value) => Math.max(0, value - 1)), 1000);
    return () => clearInterval(interval);
  }, [mode, started, timerMinutes, timeLeft]);

  const clock = useMemo(() => `${String(Math.floor(timeLeft / 60)).padStart(2, '0')}:${String(timeLeft % 60).padStart(2, '0')}`, [timeLeft]);
  const clearAttempt = () => { setStarted(false); setCurrent(0); setAnswers({}); setMarked(new Set()); setSubmitted(new Set()); setWritten(''); setWrittenSubmitted(false); setTimeLeft((timerMinutes ?? 0) * 60); };
  const chooseSubject = (nextId: string) => { const next = practiceSubjects.find((item) => item.id === nextId) ?? practiceSubjects[0]; setSubjectId(next.id); setTopicId(next.topics[0].id); clearAttempt(); };
  const chooseTopic = (nextId: string) => { setTopicId(nextId); clearAttempt(); };
  const chooseMode = (nextMode: PracticeMode) => { setMode(nextMode); clearAttempt(); };
  const chooseTimer = (minutes: number | null) => { setTimerMinutes(minutes); setTimeLeft((minutes ?? 0) * 60); };
  const startSession = () => { setCurrent(0); setAnswers({}); setMarked(new Set()); setSubmitted(new Set()); setWritten(''); setWrittenSubmitted(false); setTimeLeft((timerMinutes ?? 0) * 60); setStarted(true); };
  const selectAnswer = (option: string) => { if (!isSubmitted && (timerMinutes === null || timeLeft > 0)) setAnswers((value) => ({ ...value, [question.id]: option })); };
  const toggleReview = () => setMarked((value) => { const next = new Set(value); if (next.has(question.id)) next.delete(question.id); else next.add(question.id); return next; });
  const submitAnswer = () => setSubmitted((value) => new Set(value).add(question.id));

  return <SafeAreaView edges={['top', 'left', 'right']} style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View><Text style={[styles.eyebrow, { color: theme.primary }]}>FOCUSED PRACTICE</Text><Text style={[styles.title, { color: theme.fg }]}>Practice</Text><Text style={[styles.description, { color: theme.muted }]}>Choose a subject and topic before starting. Every question in the set will stay within that topic.</Text></View>

    {!started ? <Card style={styles.builderCard}>
      <View style={styles.builderHeading}><View style={[styles.builderIcon, { backgroundColor: theme.primarySoft }]}><Layers3 size={20} color={theme.primaryStrong} /></View><View style={styles.builderCopy}><Text style={[styles.builderTitle, { color: theme.fg }]}>Build your practice set</Text><Text style={[styles.builderHint, { color: theme.muted }]}>Subject → topic → session</Text></View>{started ? <View style={[styles.livePill, { backgroundColor: theme.successSoft }]}><View style={[styles.liveDot, { backgroundColor: theme.success }]} /><Text style={[styles.liveText, { color: theme.success }]}>LIVE</Text></View> : null}</View>
      <Text style={[styles.stepLabel, { color: theme.muted }]}>1 · SUBJECT</Text>
      <View style={styles.choiceGrid}>{practiceSubjects.map((item) => { const active = item.id === subject.id; return <Pressable key={item.id} onPress={() => chooseSubject(item.id)} style={[styles.subjectChoice, { backgroundColor: active ? theme.primarySoft : theme.sunken, borderColor: active ? theme.primary : theme.line }]}><BookOpen size={15} color={active ? theme.primaryStrong : theme.faint} /><Text numberOfLines={1} style={[styles.subjectChoiceText, { color: active ? theme.primaryStrong : theme.muted }]}>{item.title}</Text></Pressable>; })}</View>
      <Text style={[styles.stepLabel, { color: theme.muted }]}>2 · TOPIC</Text>
      <View style={styles.topicList}>{subject.topics.map((item) => { const active = item.id === topic.id; return <Pressable key={item.id} onPress={() => chooseTopic(item.id)} style={[styles.topicChoice, { backgroundColor: active ? theme.primarySoft : theme.surface, borderColor: active ? theme.primary : theme.line }]}><View style={[styles.topicRadio, { borderColor: active ? theme.primary : theme.faint, backgroundColor: active ? theme.primary : 'transparent' }]}>{active ? <CheckCircle2 size={12} color={theme.primaryFg} /> : null}</View><Text style={[styles.topicChoiceText, { color: active ? theme.fg : theme.muted }]}>{item.title}</Text><Text style={[styles.questionCount, { color: theme.faint }]}>{item.questions.length} Q</Text></Pressable>; })}</View>
      <Text style={[styles.stepLabel, { color: theme.muted }]}>3 · FORMAT</Text>
      <View style={[styles.segment, { backgroundColor: theme.sunken }]}><Pressable onPress={() => chooseMode('mcq')} style={[styles.segmentButton, mode === 'mcq' && { backgroundColor: theme.surface, borderColor: theme.line }]}><CircleHelp size={16} color={mode === 'mcq' ? theme.primaryStrong : theme.muted} /><Text style={[styles.segmentText, { color: mode === 'mcq' ? theme.primaryStrong : theme.muted }]}>MCQ set</Text></Pressable><Pressable onPress={() => chooseMode('written')} style={[styles.segmentButton, mode === 'written' && { backgroundColor: theme.surface, borderColor: theme.line }]}><PenLine size={16} color={mode === 'written' ? theme.primaryStrong : theme.muted} /><Text style={[styles.segmentText, { color: mode === 'written' ? theme.primaryStrong : theme.muted }]}>Written</Text></Pressable></View>
      {mode === 'mcq' ? <><View style={styles.timerHeading}><Text style={[styles.stepLabel, { color: theme.muted }]}>4 · TIMER</Text><View style={[styles.clock, { backgroundColor: timerMinutes === null ? theme.sunken : theme.primarySoft }]}><Clock3 size={14} color={timerMinutes === null ? theme.muted : theme.primaryStrong} /><Text style={[styles.clockText, { color: timerMinutes === null ? theme.muted : theme.primaryStrong }]}>{timerMinutes === null ? 'Off' : started ? clock : `${timerMinutes} min`}</Text></View></View><View style={styles.timerOptions}>{[5, 10, 15].map((minutes) => <Pressable key={minutes} onPress={() => chooseTimer(minutes)} style={[styles.timerOption, { borderColor: timerMinutes === minutes ? theme.primary : theme.line, backgroundColor: timerMinutes === minutes ? theme.primarySoft : theme.surface }]}><Text style={[styles.timerOptionText, { color: timerMinutes === minutes ? theme.primaryStrong : theme.muted }]}>{minutes} min</Text></Pressable>)}<Pressable onPress={() => chooseTimer(null)} style={[styles.timerOption, { borderColor: timerMinutes === null ? theme.primary : theme.line, backgroundColor: timerMinutes === null ? theme.primarySoft : theme.surface }]}><Text style={[styles.timerOptionText, { color: timerMinutes === null ? theme.primaryStrong : theme.muted }]}>Off</Text></Pressable></View></> : null}
      <Pressable onPress={startSession} style={({ pressed }) => [styles.startButton, { backgroundColor: theme.primary }, pressed && styles.pressed]}><Play size={18} fill={theme.primaryFg} color={theme.primaryFg} /><Text style={[styles.startText, { color: theme.primaryFg }]}>Start {mode === 'mcq' ? `${questions.length}-question` : 'written'} session</Text></Pressable>
    </Card> : <SessionSummary subject={subject.title} topic={topic.title} mode={mode} timer={timerMinutes === null || mode === 'written' ? 'Untimed' : clock} answered={answeredCount} total={questions.length} reviewCount={marked.size} words={written.trim() ? written.trim().split(/\s+/).length : 0} writtenSubmitted={writtenSubmitted} onChange={clearAttempt} />}

    {started && mode === 'mcq' ? <>
      <Card><View style={styles.progressHeader}><View><Text style={[styles.cardLabel, { color: theme.fg }]}>Question navigator</Text><Text style={[styles.progressCopy, { color: theme.muted }]}>{answeredCount} answered of {questions.length} · {topic.title}</Text></View><Text style={[styles.progressValue, { color: theme.primaryStrong }]}>{progress}%</Text></View><View style={[styles.progressTrack, { backgroundColor: theme.sunken }]}><View style={[styles.progressFill, { backgroundColor: theme.primary, width: `${progress}%` }]} /></View><View style={styles.legend}><Legend color={theme.success} label="Answered" /><Legend color={theme.goldStrong} label="Review" /><Legend color={theme.faint} label="Unanswered" /></View><View style={styles.navigator}>{questions.map((item, index) => { const answered = Boolean(answers[item.id]); const review = marked.has(item.id); const active = index === current; const backgroundColor = active ? theme.primary : review ? theme.goldSoft : answered ? theme.successSoft : theme.surface; const borderColor = active ? theme.primary : review ? theme.goldStrong : answered ? theme.success : theme.line; return <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Question ${index + 1}${answered ? ', answered' : ''}${review ? ', marked for review' : ''}`} onPress={() => setCurrent(index)} style={[styles.navItem, { backgroundColor, borderColor }]}><Text style={[styles.navText, { color: active ? theme.primaryFg : review ? theme.goldStrong : answered ? theme.success : theme.muted }]}>{index + 1}</Text></Pressable>; })}</View></Card>
      <Card><View style={styles.questionHeader}><View style={styles.questionContext}><Text style={[styles.questionSubject, { color: theme.primaryStrong }]}>{subject.title.toUpperCase()}</Text><Text numberOfLines={1} style={[styles.questionTopic, { color: theme.muted }]}>{topic.title} · {current + 1} of {questions.length}</Text></View><Pressable onPress={toggleReview} style={[styles.reviewButton, { backgroundColor: marked.has(question.id) ? theme.goldSoft : theme.sunken }]}><Flag size={15} color={marked.has(question.id) ? theme.goldStrong : theme.muted} /><Text style={[styles.reviewText, { color: marked.has(question.id) ? theme.goldStrong : theme.muted }]}>{marked.has(question.id) ? 'Marked' : 'Review'}</Text></Pressable></View><Text style={[styles.question, { color: theme.fg }]}>{question.prompt}</Text><View style={styles.options}>{question.options.map((option) => { const selectedThis = selected === option; const correctOption = option === question.answer; const backgroundColor = isSubmitted && correctOption ? theme.successSoft : isSubmitted && selectedThis ? theme.dangerSoft : selectedThis ? theme.primarySoft : theme.surface; const borderColor = isSubmitted && correctOption ? theme.success : isSubmitted && selectedThis ? theme.danger : selectedThis ? theme.primary : theme.line; return <Pressable key={option} disabled={isSubmitted || (timerMinutes !== null && timeLeft === 0)} onPress={() => selectAnswer(option)} style={[styles.option, { backgroundColor, borderColor }]}><View style={[styles.radio, { borderColor: selectedThis ? theme.primary : theme.faint, backgroundColor: selectedThis ? theme.primary : 'transparent' }]}>{selectedThis ? <Text style={[styles.radioCheck, { color: theme.primaryFg }]}>✓</Text> : null}</View><Text style={[styles.optionText, { color: theme.fg }]}>{option}</Text></Pressable>; })}</View>{isSubmitted ? <View style={[styles.feedback, { backgroundColor: selected === question.answer ? theme.successSoft : theme.dangerSoft }]}><Text style={[styles.feedbackTitle, { color: selected === question.answer ? theme.success : theme.danger }]}>{selected === question.answer ? 'Correct — well done.' : 'Not quite.'}</Text><Text style={[styles.feedbackText, { color: theme.muted }]}>{question.explanation}</Text></View> : null}<View style={styles.actions}><AppButton label={isSubmitted ? 'Answered' : 'Submit answer'} disabled={!selected || isSubmitted || (timerMinutes !== null && timeLeft === 0)} onPress={submitAnswer} /><Pressable onPress={() => setCurrent((index) => Math.min(index + 1, questions.length - 1))} style={[styles.next, { borderColor: theme.line, backgroundColor: theme.surface }]}><Text style={[styles.nextText, { color: theme.primaryStrong }]}>{current === questions.length - 1 ? 'Last question' : 'Next question'}</Text></Pressable></View>{timeLeft === 0 && timerMinutes !== null ? <Text style={[styles.timeUp, { color: theme.danger }]}>Time is up. Start a new session to practise again.</Text> : null}</Card>
    </> : null}

    {started && mode === 'written' ? <Card><Text style={[styles.questionSubject, { color: theme.primaryStrong }]}>{subject.title.toUpperCase()} · {topic.title.toUpperCase()}</Text><Text style={[styles.question, { color: theme.fg }]}>{topic.writtenPrompt}</Text><TextInput multiline value={written} onChangeText={setWritten} placeholder="Write a concise answer…" placeholderTextColor={theme.faint} style={[styles.answer, { color: theme.fg, borderColor: theme.line, backgroundColor: theme.sunken }]} />{writtenSubmitted ? <View style={[styles.feedback, { backgroundColor: theme.successSoft }]}><Text style={[styles.feedbackTitle, { color: theme.success }]}>Sample feedback</Text><Text style={[styles.feedbackText, { color: theme.muted }]}>{topic.writtenFeedback}</Text></View> : <AppButton label="Submit for feedback" disabled={written.trim().length < 12} onPress={() => setWrittenSubmitted(true)} />}</Card> : null}
  </ScrollView></SafeAreaView>;
}

function SessionSummary({ subject, topic, mode, timer, answered, total, reviewCount, words, writtenSubmitted, onChange }: { subject: string; topic: string; mode: PracticeMode; timer: string; answered: number; total: number; reviewCount: number; words: number; writtenSubmitted: boolean; onChange: () => void }) {
  const { theme } = useAppTheme();
  const written = mode === 'written';
  return <Card style={styles.sessionSummary}>
    <View style={styles.sessionTop}><View style={styles.sessionContext}><View style={[styles.livePill, { backgroundColor: theme.successSoft }]}><View style={[styles.liveDot, { backgroundColor: theme.success }]} /><Text style={[styles.liveText, { color: theme.success }]}>SESSION LIVE</Text></View><Text style={[styles.sessionSubject, { color: theme.fg }]}>{subject}</Text><Text numberOfLines={1} style={[styles.sessionTopic, { color: theme.muted }]}>{topic} · {written ? 'Written response' : `${total}-question MCQ`}</Text></View><Pressable accessibilityRole="button" onPress={onChange} style={({ pressed }) => [styles.changeCompact, { backgroundColor: theme.sunken, borderColor: theme.line }, pressed && styles.pressed]}><RotateCcw size={15} color={theme.primaryStrong} /><Text style={[styles.changeCompactText, { color: theme.primaryStrong }]}>Change</Text></Pressable></View>
    <View style={styles.sessionMetrics}>
      <View style={[styles.sessionMetric, { backgroundColor: theme.sunken }]}><Clock3 size={17} color={theme.primaryStrong} /><Text numberOfLines={1} adjustsFontSizeToFit style={[styles.sessionMetricValue, { color: theme.fg }]}>{timer}</Text><Text style={[styles.sessionMetricLabel, { color: theme.muted }]}>Time left</Text></View>
      <View style={[styles.sessionMetric, { backgroundColor: theme.sunken }]}><CheckCircle2 size={17} color={theme.success} /><Text style={[styles.sessionMetricValue, { color: theme.fg }]}>{written ? words : `${answered}/${total}`}</Text><Text style={[styles.sessionMetricLabel, { color: theme.muted }]}>{written ? 'Words' : 'Answered'}</Text></View>
      <View style={[styles.sessionMetric, { backgroundColor: theme.sunken }]}><Flag size={17} color={theme.goldStrong} /><Text style={[styles.sessionMetricValue, { color: theme.fg }]}>{written ? (writtenSubmitted ? 'Done' : 'Draft') : reviewCount}</Text><Text style={[styles.sessionMetricLabel, { color: theme.muted }]}>{written ? 'Status' : 'For review'}</Text></View>
    </View>
  </Card>;
}

function Legend({ color, label }: { color: string; label: string }) { const { theme } = useAppTheme(); return <View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: color }]} /><Text style={[styles.legendText, { color: theme.muted }]}>{label}</Text></View>; }

const styles = StyleSheet.create({
  safe: { flex: 1 }, content: { width: '100%', maxWidth: 680, alignSelf: 'center', padding: spacing.lg, paddingBottom: 108, gap: spacing.md }, eyebrow: { fontFamily: font.bold, fontSize: 9, letterSpacing: 1.4 }, title: { marginTop: 3, fontFamily: font.extraBold, fontSize: 30, letterSpacing: -0.8 }, description: { marginTop: 4, maxWidth: 430, fontFamily: font.regular, fontSize: 12, lineHeight: 18 },
  builderCard: { gap: 0 }, builderHeading: { flexDirection: 'row', alignItems: 'center', gap: 10 }, builderIcon: { width: 41, height: 41, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, builderCopy: { flex: 1 }, builderTitle: { fontFamily: font.extraBold, fontSize: 16, letterSpacing: -0.3 }, builderHint: { marginTop: 2, fontFamily: font.regular, fontSize: 9 }, livePill: { minHeight: 27, borderRadius: radius.pill, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 5 }, liveDot: { width: 5, height: 5, borderRadius: 3 }, liveText: { fontFamily: font.bold, fontSize: 8, letterSpacing: .8 },
  stepLabel: { marginTop: 17, marginBottom: 8, fontFamily: font.bold, fontSize: 8, letterSpacing: 1.2 }, choiceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, subjectChoice: { minHeight: 37, maxWidth: '100%', borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6 }, subjectChoiceText: { fontFamily: font.bold, fontSize: 10 }, topicList: { gap: 7 }, topicChoice: { minHeight: 43, borderWidth: 1, borderRadius: 12, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8 }, topicRadio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, topicChoiceText: { flex: 1, fontFamily: font.semibold, fontSize: 11 }, questionCount: { fontFamily: font.bold, fontSize: 8 },
  segment: { flexDirection: 'row', borderRadius: 13, padding: 4, gap: 4 }, segmentButton: { flex: 1, minHeight: 38, borderWidth: 1, borderColor: 'transparent', borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, segmentText: { fontFamily: font.bold, fontSize: 11 }, timerHeading: { marginTop: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, clock: { minHeight: 30, borderRadius: 10, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 5 }, clockText: { fontFamily: font.bold, fontSize: 10 }, timerOptions: { flexDirection: 'row', gap: 7 }, timerOption: { flex: 1, minHeight: 34, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, timerOptionText: { fontFamily: font.semibold, fontSize: 10 }, startButton: { minHeight: 47, marginTop: 17, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, startText: { fontFamily: font.bold, fontSize: 12 },
  sessionSummary: { gap: 0 }, sessionTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, sessionContext: { flex: 1, minWidth: 0 }, sessionSubject: { marginTop: 9, fontFamily: font.extraBold, fontSize: 16, letterSpacing: -0.3 }, sessionTopic: { marginTop: 3, fontFamily: font.regular, fontSize: 9 }, changeCompact: { minHeight: 35, borderWidth: 1, borderRadius: 11, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, changeCompactText: { fontFamily: font.bold, fontSize: 9 }, sessionMetrics: { marginTop: 15, flexDirection: 'row', gap: 7 }, sessionMetric: { flex: 1, minWidth: 0, minHeight: 88, borderRadius: 14, padding: 10 }, sessionMetricValue: { marginTop: 7, fontFamily: font.extraBold, fontSize: 15, letterSpacing: -0.3 }, sessionMetricLabel: { marginTop: 2, fontFamily: font.medium, fontSize: 8 },
  progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, cardLabel: { fontFamily: font.bold, fontSize: 14 }, progressCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 9 }, progressValue: { fontFamily: font.extraBold, fontSize: 18 }, progressTrack: { height: 7, borderRadius: 4, overflow: 'hidden', marginTop: 11 }, progressFill: { height: '100%', borderRadius: 4 }, legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 }, legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 }, legendDot: { width: 7, height: 7, borderRadius: 4 }, legendText: { fontFamily: font.medium, fontSize: 8 }, navigator: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 13 }, navItem: { width: 32, height: 32, borderRadius: 9, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, navText: { fontFamily: font.bold, fontSize: 10 },
  questionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, questionContext: { flex: 1, minWidth: 0 }, questionSubject: { fontFamily: font.bold, fontSize: 9, letterSpacing: 1.1 }, questionTopic: { marginTop: 3, fontFamily: font.regular, fontSize: 9 }, reviewButton: { minHeight: 31, borderRadius: 10, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 5 }, reviewText: { fontFamily: font.bold, fontSize: 9 }, question: { marginTop: 12, fontFamily: font.bold, fontSize: 17, lineHeight: 24 }, options: { gap: 8, marginVertical: 15 }, option: { minHeight: 48, borderWidth: 1, borderRadius: 12, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, radio: { height: 20, width: 20, borderRadius: 10, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' }, radioCheck: { fontFamily: font.bold, fontSize: 12 }, optionText: { flex: 1, fontFamily: font.medium, fontSize: 12, lineHeight: 17 }, feedback: { padding: 13, borderRadius: 13, gap: 6 }, feedbackTitle: { fontFamily: font.bold, fontSize: 13 }, feedbackText: { fontFamily: font.regular, fontSize: 11, lineHeight: 17 }, actions: { gap: 8, marginTop: 12 }, next: { minHeight: 42, borderWidth: 1, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, nextText: { fontFamily: font.bold, fontSize: 11 }, timeUp: { marginTop: 10, fontFamily: font.semibold, fontSize: 10, textAlign: 'center' }, pressed: { opacity: 0.74, transform: [{ scale: 0.99 }] }, answer: { minHeight: 150, borderWidth: 1, borderRadius: 13, padding: 12, textAlignVertical: 'top', fontFamily: font.regular, fontSize: 13, lineHeight: 20, marginVertical: 15 },
});
