import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card } from '@/components/ui';
import { MetricTile, ProgressBar, SessionButton } from '@/components/study-ui';
import { font, spacing } from '@/constants/theme';
import { demoStudy, formatMinutes, useDemoStudyClock } from '@/lib/demo-study';
import { useAppTheme } from '@/providers/app-providers';

export default function TrackerScreen() {
  const { theme } = useAppTheme(); const study = useDemoStudyClock();
  return <SafeAreaView edges={['left', 'right']} style={[styles.safe, { backgroundColor: theme.canvas }]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={[styles.eyebrow, { color: theme.goldStrong }]}>STUDY DISCIPLINE</Text><Text style={[styles.title, { color: theme.fg }]}>Tracker</Text><Text style={[styles.description, { color: theme.muted }]}>Small focused sessions, measured with care.</Text>
    <Card style={styles.sessionCard}><Text style={[styles.sessionLabel, { color: study.checkedIn ? theme.goldStrong : theme.primary }]}>{study.checkedIn ? 'YOUR SESSION IS ACTIVE' : 'READY WHEN YOU ARE'}</Text><SessionButton size="large" active={study.checkedIn} seconds={study.sessionSeconds} onPress={study.toggleSession} /><Text style={[styles.sessionHint, { color: theme.muted }]}>{study.checkedIn ? 'Your time is being added to today’s progress.' : 'Tap the circle to begin a focused study session.'}</Text></Card>
    <Card><View style={styles.targetTop}><View><Text style={[styles.metricLabel, { color: theme.muted }]}>{"TODAY'S FOCUS"}</Text><Text style={[styles.focusValue, { color: theme.fg }]}>{formatMinutes(study.todayMinutes)}</Text></View><Text style={[styles.target, { color: theme.primary }]}>{study.targetPercent}%<Text style={[styles.targetSuffix, { color: theme.muted }]}> / 120m</Text></Text></View><View style={{ marginTop: spacing.md }}><ProgressBar value={study.targetPercent} /></View><Text style={[styles.targetHint, { color: theme.muted }]}>{Math.max(0, demoStudy.targetMinutes - study.todayMinutes)} minutes left to reach today’s target.</Text></Card>
    <View style={styles.metricGrid}><MetricTile label="STREAK" value={`${demoStudy.streak} days`} detail="Your current run" tone="gold" /><MetricTile label="MOMENTUM" value={demoStudy.momentum} detail="Steady and strong" tone="success" /></View>
    <Card><Text style={[styles.metricLabel, { color: theme.goldStrong }]}>{demoStudy.exam.label.toUpperCase()}</Text><View style={styles.examRow}><View><Text style={[styles.examDays, { color: theme.fg }]}>{demoStudy.exam.daysLeft} days</Text><Text style={[styles.targetHint, { color: theme.muted }]}>until {demoStudy.exam.date}</Text></View><View style={[styles.pressure, { backgroundColor: theme.goldSoft }]}><Text style={[styles.pressureValue, { color: theme.goldStrong }]}>{demoStudy.exam.pressure}</Text><Text style={[styles.pressureText, { color: theme.goldStrong }]}>PRESSURE</Text></View></View><View style={{ marginTop: spacing.md }}><ProgressBar value={demoStudy.exam.pressure} color={theme.gold} /></View><Text style={[styles.targetHint, { color: theme.muted }]}>A steady pace now gives your revision time room to grow.</Text></Card>
    <View><Text style={[styles.metricLabel, { color: theme.muted }]}>YOUR READINESS</Text><View style={styles.readiness}><MetricTile label="SYLLABUS" value={`${demoStudy.syllabusPercent}%`} detail="Covered so far" /><MetricTile label="REVISIONS" value={demoStudy.revisions} detail="Intentional returns" tone="gold" /></View></View>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: spacing.xl, gap: spacing.lg, paddingBottom: spacing.xxxl, maxWidth: 720, width: '100%', alignSelf: 'center' }, eyebrow: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1.3 }, title: { fontFamily: font.extraBold, fontSize: 30, letterSpacing: -0.8 }, description: { fontFamily: font.regular, fontSize: 14, lineHeight: 21 }, sessionCard: { alignItems: 'center', paddingVertical: spacing.xl }, sessionLabel: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1.2 }, sessionHint: { fontFamily: font.regular, fontSize: 12, lineHeight: 18, textAlign: 'center' }, targetTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, metricLabel: { fontFamily: font.bold, fontSize: 10, letterSpacing: 1.1 }, focusValue: { marginTop: 4, fontFamily: font.extraBold, fontSize: 31, letterSpacing: -0.8 }, target: { fontFamily: font.extraBold, fontSize: 20 }, targetSuffix: { fontFamily: font.regular, fontSize: 12 }, targetHint: { marginTop: spacing.sm, fontFamily: font.regular, fontSize: 12, lineHeight: 18 }, metricGrid: { flexDirection: 'row', gap: spacing.md }, examRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.sm }, examDays: { fontFamily: font.extraBold, fontSize: 26, letterSpacing: -0.7 }, pressure: { width: 66, height: 66, borderRadius: 33, alignItems: 'center', justifyContent: 'center' }, pressureValue: { fontFamily: font.extraBold, fontSize: 18 }, pressureText: { fontFamily: font.bold, fontSize: 8 }, readiness: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.sm } });
