import { api } from '@/lib/api';

export type SourceKind = 'ARCHIVE';
export type AnswerFormat = 'MCQ' | 'DESCRIPTIVE' | 'CASE_STUDY';
export type PracticeSource = { course: { id: string; code: string; name: string }; practice: { id: 'practice'; kind: 'ARCHIVE'; title: string; free: true; questionCount: number; years: number[] } };
export type PracticeFilters = { sourceKind: SourceKind; accessPolicy: 'FREE' | 'PAID'; subjects: { id: string; name: string; taxonomyChapters: { id: string; name: string; lessons: { id: string; name: string; topics: { id: string; name: string }[] }[] }[] }[]; collections: ('PYQ' | 'RTP' | 'MTP' | 'ORIGINAL')[]; years: number[]; capabilities: { yearFilter: boolean; retryWrong: boolean; explanationAfterWrong: boolean } };
export type PracticeBuild = { sourceKind: SourceKind; subjectId?: string; chapterId?: string; lessonId?: string; topicId?: string; collection?: 'PYQ' | 'RTP' | 'MTP' | 'ORIGINAL'; year?: number; answerFormat: AnswerFormat; questionCount: number; timerSeconds?: number };
export type PracticeSession = { id: string; sourceKind: SourceKind; answerFormat: AnswerFormat; accessPolicy: 'FREE' | 'PAID'; questionCount: number; timerSeconds: number | null; startedAt: string; expiresAt: string | null; status: 'ACTIVE' | 'COMPLETED' | 'EXPIRED'; answeredCount?: number; correctCount?: number; wrongCount?: number; markedReviewCount?: number; navigator?: { id: string; sequence: number; navigatorState: string; attemptCount: number; final: boolean }[] };
export type PracticeQuestion = { id: string; sequence: number; kind: string; difficulty: string; promptHtml: string; caseHtml: string | null; options: { optionLabel: string; html: string; displayOrder: number }[]; navigatorState: string; attemptCount: number; final: boolean };
export async function getPracticeSources() { return (await api.get<PracticeSource>('/student/practice/sources')).data; }
export async function getPracticeFilters(sourceKind: SourceKind = 'ARCHIVE') { return (await api.get<PracticeFilters>('/student/practice/filters', { params: { sourceKind } })).data; }
export async function previewPracticeSet(input: PracticeBuild) { return (await api.post<{ eligibleQuestionCount: number; selectedQuestionCount: number; timerSeconds: number | null; accessPolicy: 'FREE' | 'PAID' }>('/student/practice/sets/preview', input)).data; }
export async function createPracticeSession(input: PracticeBuild) { return (await api.post<PracticeSession>('/student/practice/sessions', input)).data; }
export async function getPracticeSession(id: string) { return (await api.get<PracticeSession>(`/student/practice/sessions/${id}`)).data; }
export async function getPracticeQuestions(id: string) { return (await api.get<{ session: Pick<PracticeSession, 'id' | 'status' | 'accessPolicy' | 'expiresAt'>; items: PracticeQuestion[] }>(`/student/practice/sessions/${id}/questions`, { params: { page: 1, limit: 100 } })).data; }
export async function submitPracticeAnswer(sessionId: string, questionId: string, body: { answerOptionLabel?: string; answerText?: string; durationMs?: number }) { return (await api.post<{ attempt: { correct: boolean | null }; result: { navigatorState: string; retryAllowed: boolean; explanation: string | null }; session?: PracticeSession }>(`/student/practice/sessions/${sessionId}/questions/${questionId}/attempts`, { ...body, clientAttemptId: `${questionId}-${Date.now()}-${Math.random().toString(36).slice(2)}` })).data; }
export async function markPracticeReview(sessionId: string, questionId: string, marked: boolean) { return (await api.patch<{ id: string; sequence: number; navigatorState: string }>(`/student/practice/sessions/${sessionId}/questions/${questionId}/review`, { marked })).data; }
export async function completePracticeSession(id: string) { return (await api.post<PracticeSession>(`/student/practice/sessions/${id}/complete`)).data; }
type PracticeMetric = { questionsSolved: number; attempts: number; correct: number; wrong: number; durationMs: number; accuracyPercent: number | null };
export type PracticeTracker = { course: { id: string; code: string; name: string }; totals: { questionsSolved: number; attempts: number; correct: number; wrong: number; durationMs: number }; subjects: (PracticeMetric & { subjectId: string; subjectName: string })[]; chapters: (PracticeMetric & { chapterId: string; chapterName: string; subject: { id: string; name: string } })[]; topics: (PracticeMetric & { topicId: string; topicName: string; chapter: { id: string; name: string }; subject: { id: string; name: string } })[]; activity: { date: string; attempts: number; correct: number; wrong: number; durationMs: number }[]; weakAreas: null | (PracticeMetric & { topicId: string; topicName: string; chapter: { id: string; name: string }; subject: { id: string; name: string } })[]; capabilities: { conceptWeakAreas: boolean; weakAreaGranularity: 'TOPIC' } };
export async function getPracticeTracker() { return (await api.get<PracticeTracker>('/student/practice/tracker')).data; }
