import { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { BookOpen, CheckCircle2, FileText, FolderTree, GraduationCap, Layers3, LockKeyhole, PackageCheck, Plus, X } from 'lucide-react-native';

import { AdminShell } from '@/components/admin-shell';
import { font, radius, spacing } from '@/constants/theme';
import { useAdminCourseStore } from '@/lib/admin-course-store';
import { formatInr, paidNotes, paidPackages, type PaidNote, type PaidPackage } from '@/lib/demo-admin';
import { useAppTheme } from '@/providers/app-providers';

type PageView = 'structure' | 'paid';
type PaidView = 'notes' | 'packages';
type CreateRequest = { mode: 'course' | 'category' | 'subject'; courseId?: string; categoryId?: string; parentName?: string };

export default function AdminCourses() {
  const { theme } = useAppTheme();
  const params = useLocalSearchParams<{ view?: string; kind?: string }>();
  const courses = useAdminCourseStore((state) => state.courses);
  const addCourse = useAdminCourseStore((state) => state.addCourse);
  const addCategory = useAdminCourseStore((state) => state.addCategory);
  const addSubject = useAdminCourseStore((state) => state.addSubject);
  const [view, setView] = useState<PageView>(params.view === 'paid' ? 'paid' : 'structure');
  const [paidView, setPaidView] = useState<PaidView>(params.kind === 'packages' ? 'packages' : 'notes');
  const [courseId, setCourseId] = useState(courses[0]?.id ?? '');
  const [courseFilter, setCourseFilter] = useState('All');
  const [createRequest, setCreateRequest] = useState<CreateRequest | null>(null);
  const selectedCourse = courses.find((course) => course.id === courseId) ?? courses[0];
  const categoryCount = courses.reduce((total, course) => total + course.categories.length, 0);
  const subjectCount = courses.reduce((total, course) => total + course.categories.reduce((count, category) => count + category.subjects.length, 0), 0);
  const paidItems = paidView === 'notes' ? paidNotes : paidPackages;
  const visiblePaidItems = paidItems.filter((item) => courseFilter === 'All' || item.course === courseFilter);
  const addAction = <Pressable onPress={() => setCreateRequest({ mode: 'course' })} style={({ pressed }) => [styles.addCourse, { backgroundColor: theme.primary }, pressed && styles.pressed]}><Plus size={17} color={theme.primaryFg} /><Text style={[styles.addCourseText, { color: theme.primaryFg }]}>Course</Text></Pressable>;

  const submitCreation = (name: string) => {
    if (!createRequest) return;
    if (createRequest.mode === 'course') addCourse(name);
    if (createRequest.mode === 'category' && createRequest.courseId) addCategory(createRequest.courseId, name);
    if (createRequest.mode === 'subject' && createRequest.courseId && createRequest.categoryId) addSubject(createRequest.courseId, createRequest.categoryId, name);
    setCreateRequest(null);
  };

  return <>
    <AdminShell eyebrow="ACADEMIC STRUCTURE" title="Courses" description="Create course hierarchy on mobile and review paid content published from the website." action={view === 'structure' ? addAction : undefined}>
      <View style={[styles.permission, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.permissionIcon, { backgroundColor: theme.primarySoft }]}><LockKeyhole size={18} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.permissionTitle, { color: theme.fg }]}>Structure only on mobile</Text><Text style={[styles.permissionCopy, { color: theme.muted }]}>Create courses, subcategories and subjects here. Note and package uploads remain available only on the website.</Text></View></View>

      <View style={[styles.pageSwitch, { backgroundColor: theme.sunken, borderColor: theme.line }]}><Pressable onPress={() => setView('structure')} style={[styles.pageSwitchItem, view === 'structure' && { backgroundColor: theme.surface, borderColor: theme.lineStrong }]}><FolderTree size={17} color={view === 'structure' ? theme.primaryStrong : theme.muted} /><Text style={[styles.pageSwitchText, { color: view === 'structure' ? theme.fg : theme.muted }]}>Structure</Text></Pressable><Pressable onPress={() => setView('paid')} style={[styles.pageSwitchItem, view === 'paid' && { backgroundColor: theme.surface, borderColor: theme.lineStrong }]}><PackageCheck size={17} color={view === 'paid' ? theme.primaryStrong : theme.muted} /><Text style={[styles.pageSwitchText, { color: view === 'paid' ? theme.fg : theme.muted }]}>Paid content</Text></Pressable></View>

      {view === 'structure' ? <>
        <View style={styles.metrics}><Metric icon={GraduationCap} value={String(courses.length)} label="Courses" tone="primary" /><Metric icon={Layers3} value={String(categoryCount)} label="Subcategories" tone="gold" /><Metric icon={BookOpen} value={String(subjectCount)} label="Subjects" tone="success" /></View>
        <View><Text style={[styles.sectionTitle, { color: theme.fg }]}>Courses and exams</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>Select one to manage its levels and subjects</Text></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.courseTabs}>{courses.map((course) => { const active = course.id === selectedCourse?.id; const count = course.categories.reduce((total, category) => total + category.subjects.length, 0); return <Pressable key={course.id} onPress={() => setCourseId(course.id)} style={[styles.courseTab, { backgroundColor: active ? theme.primarySoft : theme.surface, borderColor: active ? theme.primary : theme.line }]}><Text style={[styles.courseTabName, { color: active ? theme.primaryStrong : theme.fg }]}>{course.name}</Text><Text style={[styles.courseTabMeta, { color: theme.muted }]}>{course.categories.length} levels · {count} subjects</Text></Pressable>; })}</ScrollView>

        {selectedCourse ? <View style={[styles.coursePanel, { backgroundColor: theme.surface, borderColor: theme.line }]}>
          <View style={styles.coursePanelTop}><View style={[styles.courseMark, { backgroundColor: theme.primarySoft }]}><GraduationCap size={22} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.coursePanelEyebrow, { color: theme.primary }]}>COURSE / EXAM</Text><Text style={[styles.coursePanelTitle, { color: theme.fg }]}>{selectedCourse.name}</Text><Text style={[styles.coursePanelMeta, { color: theme.muted }]}>{selectedCourse.categories.length} subcategories</Text></View><Pressable onPress={() => setCreateRequest({ mode: 'category', courseId: selectedCourse.id, parentName: selectedCourse.name })} style={[styles.smallAdd, { backgroundColor: theme.primarySoft }]}><Plus size={15} color={theme.primaryStrong} /><Text style={[styles.smallAddText, { color: theme.primaryStrong }]}>Level</Text></Pressable></View>
          <View style={styles.categoryList}>{selectedCourse.categories.map((category, categoryIndex) => <View key={category.id} style={[styles.category, { backgroundColor: theme.sunken, borderColor: theme.line }]}>
            <View style={styles.categoryTop}><View style={[styles.categoryIndex, { backgroundColor: theme.goldSoft }]}><Text style={[styles.categoryIndexText, { color: theme.goldStrong }]}>{String(categoryIndex + 1).padStart(2, '0')}</Text></View><View style={styles.flex}><Text style={[styles.categoryLabel, { color: theme.goldStrong }]}>SUBCATEGORY / LEVEL</Text><Text style={[styles.categoryTitle, { color: theme.fg }]}>{category.name}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Add subject to ${category.name}`} onPress={() => setCreateRequest({ mode: 'subject', courseId: selectedCourse.id, categoryId: category.id, parentName: `${selectedCourse.name} → ${category.name}` })} style={[styles.iconAdd, { borderColor: theme.line, backgroundColor: theme.surface }]}><Plus size={17} color={theme.primaryStrong} /></Pressable></View>
            <View style={styles.subjectList}>{category.subjects.map((subject) => <View key={subject.id} style={[styles.subjectRow, { borderTopColor: theme.line }]}><View style={[styles.subjectIcon, { backgroundColor: theme.primarySoft }]}><BookOpen size={15} color={theme.primaryStrong} /></View><Text style={[styles.subjectName, { color: theme.fg }]}>{subject.name}</Text><CheckCircle2 size={15} color={theme.success} /></View>)}</View>
            {!category.subjects.length ? <Text style={[styles.emptySubjects, { color: theme.muted }]}>No subjects yet. Use + to add the first one.</Text> : null}
          </View>)}</View>
          {!selectedCourse.categories.length ? <View style={styles.emptyCourse}><Layers3 size={23} color={theme.faint} /><Text style={[styles.emptyTitle, { color: theme.fg }]}>No subcategories yet</Text><Text style={[styles.emptyCopy, { color: theme.muted }]}>Add a level such as Mains, Intermediate or UG.</Text></View> : null}
        </View> : null}
      </> : <PaidContent view={paidView} setView={setPaidView} courseFilter={courseFilter} setCourseFilter={setCourseFilter} items={visiblePaidItems} />}
    </AdminShell>
    <CreationModal request={createRequest} onClose={() => setCreateRequest(null)} onSubmit={submitCreation} />
  </>;
}

function Metric({ icon: Icon, value, label, tone }: { icon: typeof BookOpen; value: string; label: string; tone: 'primary' | 'gold' | 'success' }) {
  const { theme } = useAppTheme(); const color = tone === 'gold' ? theme.goldStrong : tone === 'success' ? theme.success : theme.primaryStrong; const background = tone === 'gold' ? theme.goldSoft : tone === 'success' ? theme.successSoft : theme.primarySoft;
  return <View style={[styles.metric, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.metricIcon, { backgroundColor: background }]}><Icon size={17} color={color} /></View><Text style={[styles.metricValue, { color: theme.fg }]}>{value}</Text><Text style={[styles.metricLabel, { color: theme.muted }]}>{label}</Text></View>;
}

function PaidContent({ view, setView, courseFilter, setCourseFilter, items }: { view: PaidView; setView: (view: PaidView) => void; courseFilter: string; setCourseFilter: (value: string) => void; items: (PaidNote | PaidPackage)[] }) {
  const { theme } = useAppTheme();
  return <>
    <View style={styles.paidHeading}><View><Text style={[styles.sectionTitle, { color: theme.fg }]}>Existing paid content</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>Published on the website · read-only on mobile</Text></View><View style={[styles.readOnly, { backgroundColor: theme.primarySoft }]}><LockKeyhole size={13} color={theme.primaryStrong} /><Text style={[styles.readOnlyText, { color: theme.primaryStrong }]}>READ ONLY</Text></View></View>
    <View style={[styles.contentSwitch, { backgroundColor: theme.sunken }]}><Pressable onPress={() => setView('notes')} style={[styles.contentSwitchItem, view === 'notes' && { backgroundColor: theme.surface }]}><FileText size={16} color={view === 'notes' ? theme.primaryStrong : theme.muted} /><Text style={[styles.contentSwitchText, { color: view === 'notes' ? theme.fg : theme.muted }]}>Paid notes</Text></Pressable><Pressable onPress={() => setView('packages')} style={[styles.contentSwitchItem, view === 'packages' && { backgroundColor: theme.surface }]}><PackageCheck size={16} color={view === 'packages' ? theme.goldStrong : theme.muted} /><Text style={[styles.contentSwitchText, { color: view === 'packages' ? theme.fg : theme.muted }]}>Packages</Text></Pressable></View>
    <View style={styles.filters}>{['All', 'JEE', 'CA', 'NEET'].map((course) => <Pressable key={course} onPress={() => setCourseFilter(course)} style={[styles.filter, { backgroundColor: courseFilter === course ? theme.primarySoft : theme.surface, borderColor: courseFilter === course ? theme.primary : theme.line }]}><Text style={[styles.filterText, { color: courseFilter === course ? theme.primaryStrong : theme.muted }]}>{course}</Text></Pressable>)}</View>
    <View style={styles.paidList}>{items.map((item) => {
      const note = 'pages' in item;
      return <View key={item.id} style={[styles.paidRow, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.paidIcon, { backgroundColor: note ? theme.primarySoft : theme.goldSoft }]}>{note ? <FileText size={19} color={theme.primaryStrong} /> : <PackageCheck size={19} color={theme.goldStrong} />}</View><View style={styles.flex}><Text numberOfLines={1} style={[styles.paidTitle, { color: theme.fg }]}>{item.title}</Text><Text style={[styles.paidMeta, { color: theme.muted }]}>{item.course} · {item.category} · {note ? `${item.pages} pages` : `${item.lessonCount} lessons`}</Text></View><View style={styles.priceColumn}><Text style={[styles.price, { color: theme.fg }]}>{formatInr(item.price)}</Text><Text style={[styles.published, { color: theme.success }]}>Published</Text></View></View>;
    })}</View>
    {!items.length ? <View style={[styles.noPaid, { backgroundColor: theme.surface, borderColor: theme.line }]}><Text style={[styles.emptyTitle, { color: theme.fg }]}>No matching content</Text><Text style={[styles.emptyCopy, { color: theme.muted }]}>Choose another course filter.</Text></View> : null}
  </>;
}

function CreationModal({ request, onClose, onSubmit }: { request: CreateRequest | null; onClose: () => void; onSubmit: (name: string) => void }) {
  const { theme } = useAppTheme(); const [name, setName] = useState('');
  if (!request) return null;
  const config = request.mode === 'course' ? { eyebrow: 'NEW COURSE / EXAM', title: 'Create course', placeholder: 'Example: UPSC' } : request.mode === 'category' ? { eyebrow: 'NEW SUBCATEGORY', title: `Add level to ${request.parentName}`, placeholder: 'Example: Mains' } : { eyebrow: 'NEW SUBJECT / PHASE', title: `Add inside ${request.parentName}`, placeholder: 'Example: Mathematics or Phase 1' };
  const close = () => { setName(''); onClose(); };
  const submit = () => { const value = name.trim(); if (!value) return; setName(''); onSubmit(value); };
  return <Modal visible transparent animationType="none" onRequestClose={close}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.modalRoot}><Pressable style={styles.backdrop} onPress={close}><Pressable onPress={(event) => event.stopPropagation()} style={[styles.sheet, { backgroundColor: theme.elevated, borderColor: theme.lineStrong }]}><View style={styles.sheetTop}><View><Text style={[styles.sheetEyebrow, { color: theme.primary }]}>{config.eyebrow}</Text><Text style={[styles.sheetTitle, { color: theme.fg }]}>{config.title}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={close} style={[styles.close, { backgroundColor: theme.sunken }]}><X size={18} color={theme.muted} /></Pressable></View><Text style={[styles.fieldLabel, { color: theme.muted }]}>Name</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder={config.placeholder} placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /><Pressable disabled={!name.trim()} onPress={submit} style={({ pressed }) => [styles.submit, { backgroundColor: theme.primary }, !name.trim() && styles.disabled, pressed && styles.pressed]}><Plus size={17} color={theme.primaryFg} /><Text style={[styles.submitText, { color: theme.primaryFg }]}>Add {request.mode === 'category' ? 'subcategory' : request.mode}</Text></Pressable></Pressable></Pressable></KeyboardAvoidingView></Modal>;
}

const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 }, addCourse: { minHeight: 39, borderRadius: 12, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 5 }, addCourseText: { fontFamily: font.bold, fontSize: 10 }, pressed: { opacity: .72, transform: [{ scale: .98 }] },
  permission: { minHeight: 81, borderWidth: 1, borderRadius: 17, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, permissionIcon: { width: 41, height: 41, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, permissionTitle: { fontFamily: font.bold, fontSize: 12 }, permissionCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 9, lineHeight: 14 },
  pageSwitch: { flexDirection: 'row', borderWidth: 1, borderRadius: 15, padding: 4, gap: 4 }, pageSwitchItem: { flex: 1, height: 42, borderWidth: 1, borderColor: 'transparent', borderRadius: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, pageSwitchText: { fontFamily: font.bold, fontSize: 11 },
  metrics: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, minWidth: 0, minHeight: 102, borderWidth: 1, borderRadius: 17, padding: 11 }, metricIcon: { width: 31, height: 31, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, metricValue: { marginTop: 7, fontFamily: font.extraBold, fontSize: 18 }, metricLabel: { marginTop: 2, fontFamily: font.medium, fontSize: 8 },
  sectionTitle: { fontFamily: font.extraBold, fontSize: 17, letterSpacing: -.3 }, sectionHint: { marginTop: 3, fontFamily: font.regular, fontSize: 9 }, courseTabs: { gap: 8, paddingRight: spacing.lg }, courseTab: { minWidth: 118, minHeight: 57, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, justifyContent: 'center' }, courseTabName: { fontFamily: font.extraBold, fontSize: 13 }, courseTabMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 8 },
  coursePanel: { borderWidth: 1, borderRadius: 20, padding: 14 }, coursePanelTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, courseMark: { width: 45, height: 45, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, coursePanelEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.1 }, coursePanelTitle: { marginTop: 2, fontFamily: font.extraBold, fontSize: 18 }, coursePanelMeta: { marginTop: 2, fontFamily: font.regular, fontSize: 8 }, smallAdd: { minHeight: 34, borderRadius: 11, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 4 }, smallAddText: { fontFamily: font.bold, fontSize: 9 }, categoryList: { marginTop: 14, gap: 10 }, category: { borderWidth: 1, borderRadius: 16, padding: 11 }, categoryTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, categoryIndex: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, categoryIndexText: { fontFamily: font.extraBold, fontSize: 9 }, categoryLabel: { fontFamily: font.bold, fontSize: 7, letterSpacing: 1 }, categoryTitle: { marginTop: 2, fontFamily: font.bold, fontSize: 12 }, iconAdd: { width: 34, height: 34, borderWidth: 1, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, subjectList: { marginTop: 8 }, subjectRow: { minHeight: 43, borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 8 }, subjectIcon: { width: 29, height: 29, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, subjectName: { flex: 1, fontFamily: font.semibold, fontSize: 10 }, emptySubjects: { marginTop: 11, fontFamily: font.regular, fontSize: 9 }, emptyCourse: { minHeight: 150, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { marginTop: 8, fontFamily: font.bold, fontSize: 13 }, emptyCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 9 },
  paidHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, readOnly: { minHeight: 28, borderRadius: radius.pill, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 }, readOnlyText: { fontFamily: font.bold, fontSize: 7, letterSpacing: .7 }, contentSwitch: { flexDirection: 'row', borderRadius: 14, padding: 4, gap: 4 }, contentSwitchItem: { flex: 1, minHeight: 39, borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, contentSwitchText: { fontFamily: font.bold, fontSize: 10 }, filters: { flexDirection: 'row', gap: 7 }, filter: { flex: 1, minHeight: 33, borderWidth: 1, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center' }, filterText: { fontFamily: font.bold, fontSize: 8 }, paidList: { gap: spacing.sm }, paidRow: { minHeight: 77, borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9 }, paidIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, paidTitle: { fontFamily: font.bold, fontSize: 11 }, paidMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, priceColumn: { alignItems: 'flex-end' }, price: { fontFamily: font.bold, fontSize: 11 }, published: { marginTop: 3, fontFamily: font.bold, fontSize: 8 }, noPaid: { minHeight: 140, borderWidth: 1, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.68)' }, sheet: { width: '100%', maxWidth: 680, alignSelf: 'center', borderWidth: 1, borderBottomWidth: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing.xl, paddingBottom: 30 }, sheetTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }, sheetEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.2 }, sheetTitle: { marginTop: 4, maxWidth: 270, fontFamily: font.extraBold, fontSize: 19, lineHeight: 25 }, close: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, fieldLabel: { marginTop: 19, marginBottom: 7, fontFamily: font.bold, fontSize: 9, letterSpacing: .8 }, input: { minHeight: 49, borderWidth: 1, borderRadius: 13, paddingHorizontal: 12, fontFamily: font.regular, fontSize: 13 }, submit: { minHeight: 47, marginTop: 13, borderRadius: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, submitText: { fontFamily: font.bold, fontSize: 11 }, disabled: { opacity: .45 },
});
