import { useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { BookOpen, CheckCircle2, ChevronDown, ChevronRight, FileText, FolderTree, GraduationCap, Layers3, LockKeyhole, PackageCheck, Plus, Search, X } from 'lucide-react-native';

import { AdminShell } from '@/components/admin-shell';
import { font, radius, spacing } from '@/constants/theme';
import { useAdminCourseStore } from '@/lib/admin-course-store';
import { formatInr, paidNotes, paidPackages } from '@/lib/demo-admin';
import { useAppTheme } from '@/providers/app-providers';

type PageView = 'structure' | 'paid';
type PaidView = 'notes' | 'packages';
type CreateRequest = { mode: 'course' | 'category' | 'subject'; courseId?: string; categoryId?: string; parentName?: string };

export default function AdminCourses() {
  const { theme } = useAppTheme();
  const params = useLocalSearchParams<{ view?: string; kind?: string }>();
  const courses = useAdminCourseStore((state) => state.courses);
  const addCourse = useAdminCourseStore((state) => state.addCourse);
  const addCategory = useAdminCourseStore((state) => state.addCategory);
  const addSubject = useAdminCourseStore((state) => state.addSubject);
  const [view, setView] = useState<PageView>(params.view === 'paid' ? 'paid' : 'structure');
  const [paidView, setPaidView] = useState<PaidView>(params.kind === 'packages' ? 'packages' : 'notes');
  const [courseId, setCourseId] = useState(courses[0]?.id ?? '');
  const [expandedCategoryId, setExpandedCategoryId] = useState(courses[0]?.categories[0]?.id ?? '');
  const [createRequest, setCreateRequest] = useState<CreateRequest | null>(null);
  const selectedCourse = courses.find((course) => course.id === courseId) ?? courses[0];
  const categoryCount = courses.reduce((total, course) => total + course.categories.length, 0);
  const subjectCount = courses.reduce((total, course) => total + course.categories.reduce((count, category) => count + category.subjects.length, 0), 0);
  const addAction = <Pressable accessibilityRole="button" accessibilityLabel="Add course" onPress={() => setCreateRequest({ mode: 'course' })} style={({ pressed }) => [styles.addCourse, { backgroundColor: theme.primary }, pressed && styles.pressed]}><Plus size={16} color={theme.primaryFg} /><Text style={[styles.addCourseText, { color: theme.primaryFg }]}>Course</Text></Pressable>;

  const selectCourse = (nextCourseId: string) => {
    const nextCourse = courses.find((course) => course.id === nextCourseId);
    setCourseId(nextCourseId);
    setExpandedCategoryId(nextCourse?.categories[0]?.id ?? '');
  };
  const submitCreation = (name: string) => {
    if (!createRequest) return;
    if (createRequest.mode === 'course') addCourse(name);
    if (createRequest.mode === 'category' && createRequest.courseId) addCategory(createRequest.courseId, name);
    if (createRequest.mode === 'subject' && createRequest.courseId && createRequest.categoryId) addSubject(createRequest.courseId, createRequest.categoryId, name);
    setCreateRequest(null);
  };

  return <>
    <AdminShell eyebrow="ACADEMIC STRUCTURE" title="Courses" description="Keep course hierarchy organised and review website-published material." action={view === 'structure' ? addAction : undefined}>
      <View style={[styles.pageSwitch, { backgroundColor: theme.sunken, borderColor: theme.line }]}><Pressable onPress={() => setView('structure')} style={[styles.pageSwitchItem, view === 'structure' && { backgroundColor: theme.surface, borderColor: theme.lineStrong }]}><FolderTree size={16} color={view === 'structure' ? theme.primaryStrong : theme.muted} /><Text style={[styles.pageSwitchText, { color: view === 'structure' ? theme.fg : theme.muted }]}>Structure</Text></Pressable><Pressable onPress={() => setView('paid')} style={[styles.pageSwitchItem, view === 'paid' && { backgroundColor: theme.surface, borderColor: theme.lineStrong }]}><PackageCheck size={16} color={view === 'paid' ? theme.primaryStrong : theme.muted} /><Text style={[styles.pageSwitchText, { color: view === 'paid' ? theme.fg : theme.muted }]}>Catalogue</Text></Pressable></View>

      {view === 'structure' ? <>
        <LinearGradient colors={['#1B2543', '#121A2B', '#111416']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.architectureHero}>
          <View style={styles.heroOrbit} /><View style={styles.heroTop}><View style={styles.heroIdentity}><View style={styles.heroIcon}><FolderTree size={20} color="#C7D2FF" /></View><View><Text style={styles.heroEyebrow}>COURSE ARCHITECTURE</Text><Text style={styles.heroTitle}>Organised for every exam.</Text></View></View><View style={styles.livePill}><View style={styles.liveDot} /><Text style={styles.liveText}>READY</Text></View></View>
          <View style={styles.heroMetrics}><HeroMetric value={String(courses.length)} label="Courses" /><View style={styles.heroDivider} /><HeroMetric value={String(categoryCount)} label="Levels" /><View style={styles.heroDivider} /><HeroMetric value={String(subjectCount)} label="Subjects" /></View>
        </LinearGradient>

        <View><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>COURSES & EXAMS</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>Choose a learning track</Text><Text style={[styles.sectionHint, { color: theme.muted }]}>Each track contains its categories and subjects</Text></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.courseTabs}>{courses.map((course) => { const active = course.id === selectedCourse?.id; const count = course.categories.reduce((total, category) => total + category.subjects.length, 0); return <Pressable key={course.id} onPress={() => selectCourse(course.id)} style={[styles.courseTab, { backgroundColor: active ? theme.primarySoft : theme.surface, borderColor: active ? theme.primary : theme.line }]}><View style={styles.courseTabTop}><GraduationCap size={16} color={active ? theme.primaryStrong : theme.muted} /><Text style={[styles.courseTabName, { color: active ? theme.primaryStrong : theme.fg }]}>{course.name}</Text></View><Text style={[styles.courseTabMeta, { color: theme.muted }]}>{course.categories.length} levels · {count} subjects</Text></Pressable>; })}</ScrollView>

        {selectedCourse ? <View style={[styles.coursePanel, { backgroundColor: theme.surface, borderColor: theme.line }]}>
          <View style={styles.coursePanelTop}><View style={[styles.courseMark, { backgroundColor: theme.primarySoft }]}><GraduationCap size={21} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.panelEyebrow, { color: theme.primary }]}>SELECTED COURSE</Text><Text style={[styles.coursePanelTitle, { color: theme.fg }]}>{selectedCourse.name}</Text><Text style={[styles.coursePanelMeta, { color: theme.muted }]}>{selectedCourse.categories.length} categories in this track</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Add category to ${selectedCourse.name}`} onPress={() => setCreateRequest({ mode: 'category', courseId: selectedCourse.id, parentName: selectedCourse.name })} style={[styles.smallAdd, { backgroundColor: theme.primarySoft }]}><Plus size={14} color={theme.primaryStrong} /><Text style={[styles.smallAddText, { color: theme.primaryStrong }]}>Level</Text></Pressable></View>

          <View style={styles.categoryList}>{selectedCourse.categories.map((category, categoryIndex) => { const expanded = expandedCategoryId === category.id; return <View key={category.id} style={[styles.category, { backgroundColor: theme.sunken, borderColor: expanded ? theme.lineStrong : theme.line }]}>
            <View style={styles.categoryHeader}><Pressable accessibilityRole="button" accessibilityState={{ expanded }} onPress={() => setExpandedCategoryId(expanded ? '' : category.id)} style={({ pressed }) => [styles.categoryToggle, pressed && styles.pressed]}><View style={[styles.categoryIndex, { backgroundColor: theme.goldSoft }]}><Text style={[styles.categoryIndexText, { color: theme.goldStrong }]}>{String(categoryIndex + 1).padStart(2, '0')}</Text></View><View style={styles.flex}><Text style={[styles.categoryLabel, { color: theme.goldStrong }]}>CATEGORY / LEVEL</Text><Text style={[styles.categoryTitle, { color: theme.fg }]}>{category.name}</Text><Text style={[styles.categoryMeta, { color: theme.muted }]}>{category.subjects.length} subjects</Text></View><ChevronDown size={17} color={theme.muted} style={{ transform: [{ rotate: expanded ? '180deg' : '0deg' }] }} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Add subject to ${category.name}`} onPress={() => setCreateRequest({ mode: 'subject', courseId: selectedCourse.id, categoryId: category.id, parentName: `${selectedCourse.name} → ${category.name}` })} style={[styles.iconAdd, { borderColor: theme.line, backgroundColor: theme.surface }]}><Plus size={16} color={theme.primaryStrong} /></Pressable></View>
            {expanded ? <View style={[styles.subjectList, { borderTopColor: theme.line }]}>{category.subjects.map((subject, subjectIndex) => <View key={subject.id} style={styles.subjectRow}><View style={[styles.subjectIndex, { backgroundColor: theme.primarySoft }]}><Text style={[styles.subjectIndexText, { color: theme.primaryStrong }]}>{subjectIndex + 1}</Text></View><BookOpen size={14} color={theme.muted} /><Text numberOfLines={2} style={[styles.subjectName, { color: theme.fg }]}>{subject.name}</Text><CheckCircle2 size={14} color={theme.success} /></View>)}{!category.subjects.length ? <View style={styles.emptySubjects}><BookOpen size={18} color={theme.faint} /><Text style={[styles.emptySubjectsText, { color: theme.muted }]}>No subjects yet. Use + to add the first one.</Text></View> : null}</View> : null}
          </View>; })}</View>
          {!selectedCourse.categories.length ? <View style={styles.emptyCourse}><Layers3 size={23} color={theme.faint} /><Text style={[styles.emptyTitle, { color: theme.fg }]}>No categories yet</Text><Text style={[styles.emptyCopy, { color: theme.muted }]}>Add a level such as Mains, Intermediate or UG.</Text></View> : null}
        </View> : null}

        <View style={[styles.permission, { backgroundColor: theme.primarySoft, borderColor: theme.line }]}><View style={[styles.permissionIcon, { backgroundColor: theme.surface }]}><LockKeyhole size={17} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.permissionTitle, { color: theme.primaryStrong }]}>Mobile structure controls</Text><Text style={[styles.permissionCopy, { color: theme.muted }]}>Courses, categories and subjects can be arranged here. Study-file publishing stays on the website.</Text></View></View>
      </> : <CatalogueContent view={paidView} setView={setPaidView} />}
    </AdminShell>
    <CreationModal request={createRequest} onClose={() => setCreateRequest(null)} onSubmit={submitCreation} />
  </>;
}

function HeroMetric({ value, label }: { value: string; label: string }) { return <View style={styles.heroMetric}><Text style={styles.heroMetricValue}>{value}</Text><Text style={styles.heroMetricLabel}>{label}</Text></View>; }

function CatalogueContent({ view, setView }: { view: PaidView; setView: (view: PaidView) => void }) {
  const { theme } = useAppTheme();
  const [courseFilter, setCourseFilter] = useState('All');
  const [query, setQuery] = useState('');
  const items = view === 'notes' ? paidNotes : paidPackages;
  const visibleItems = items.filter((item) => (courseFilter === 'All' || item.course === courseFilter) && (!query.trim() || `${item.title} ${item.course} ${item.category}`.toLowerCase().includes(query.trim().toLowerCase())));
  const totalValue = items.reduce((sum, item) => sum + item.price, 0);

  return <>
    <LinearGradient colors={['#1A2D2A', '#121D1B', '#111416']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.catalogueHero}><View style={styles.heroOrbit} /><View style={styles.catalogueHeroTop}><View style={styles.heroIdentity}><View style={styles.catalogueHeroIcon}><PackageCheck size={20} color="#7BDDB6" /></View><View><Text style={styles.catalogueEyebrow}>PUBLISHED CATALOGUE</Text><Text style={styles.catalogueTitle}>{paidNotes.length} notes · {paidPackages.length} packages</Text><Text style={styles.catalogueHint}>Available study material from the website</Text></View></View><View style={styles.readOnlyDark}><LockKeyhole size={12} color="#C9D2DD" /><Text style={styles.readOnlyDarkText}>READ ONLY</Text></View></View><View style={styles.catalogueStats}><Text style={styles.catalogueStat}>{items.length} {view}</Text><Text style={styles.catalogueStatDot}>•</Text><Text style={styles.catalogueStat}>{formatInr(totalValue)} listed value</Text></View></LinearGradient>

    <View style={[styles.contentSwitch, { backgroundColor: theme.sunken, borderColor: theme.line }]}><Pressable onPress={() => setView('notes')} style={[styles.contentSwitchItem, view === 'notes' && { backgroundColor: theme.surface }]}><FileText size={16} color={view === 'notes' ? theme.primaryStrong : theme.muted} /><Text style={[styles.contentSwitchText, { color: view === 'notes' ? theme.fg : theme.muted }]}>Paid notes</Text></Pressable><Pressable onPress={() => setView('packages')} style={[styles.contentSwitchItem, view === 'packages' && { backgroundColor: theme.surface }]}><PackageCheck size={16} color={view === 'packages' ? theme.goldStrong : theme.muted} /><Text style={[styles.contentSwitchText, { color: view === 'packages' ? theme.fg : theme.muted }]}>Packages</Text></Pressable></View>

    <View style={[styles.searchPanel, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={styles.searchRow}><Search size={17} color={theme.faint} /><TextInput value={query} onChangeText={setQuery} placeholder={`Search ${view}`} placeholderTextColor={theme.faint} style={[styles.searchInput, { color: theme.fg }]} />{query ? <Pressable onPress={() => setQuery('')}><Text style={[styles.clearText, { color: theme.primaryStrong }]}>Clear</Text></Pressable> : null}</View><View style={[styles.searchRule, { backgroundColor: theme.line }]} /><View style={styles.filters}>{['All', 'JEE', 'CA', 'NEET'].map((course) => <Pressable key={course} onPress={() => setCourseFilter(course)} style={[styles.filter, { backgroundColor: courseFilter === course ? theme.primarySoft : theme.sunken, borderColor: courseFilter === course ? theme.primary : 'transparent' }]}><Text style={[styles.filterText, { color: courseFilter === course ? theme.primaryStrong : theme.muted }]}>{course}</Text></Pressable>)}</View></View>

    <View style={styles.catalogueHeading}><View><Text style={[styles.sectionEyebrow, { color: theme.primary }]}>AVAILABLE NOW</Text><Text style={[styles.sectionTitle, { color: theme.fg }]}>{view === 'notes' ? 'Published notes' : 'Published packages'}</Text></View><Text style={[styles.resultCount, { color: theme.muted }]}>{visibleItems.length} shown</Text></View>
    <View style={styles.paidList}>{visibleItems.map((item) => { const note = 'pages' in item; return <View key={item.id} style={[styles.paidRow, { backgroundColor: theme.surface, borderColor: theme.line }]}><View style={[styles.paidIcon, { backgroundColor: note ? theme.primarySoft : theme.goldSoft }]}>{note ? <FileText size={18} color={theme.primaryStrong} /> : <PackageCheck size={18} color={theme.goldStrong} />}</View><View style={styles.flex}><Text numberOfLines={1} style={[styles.paidTitle, { color: theme.fg }]}>{item.title}</Text><Text numberOfLines={1} style={[styles.paidMeta, { color: theme.muted }]}>{item.course} · {item.category} · {note ? `${item.pages} pages` : `${item.lessonCount} lessons`}</Text><View style={[styles.publishedPill, { backgroundColor: theme.successSoft }]}><View style={[styles.publishedDot, { backgroundColor: theme.success }]} /><Text style={[styles.published, { color: theme.success }]}>PUBLISHED</Text></View></View><View style={styles.priceColumn}><Text style={[styles.price, { color: theme.fg }]}>{formatInr(item.price)}</Text><ChevronRight size={15} color={theme.faint} /></View></View>; })}</View>
    {!visibleItems.length ? <View style={[styles.noPaid, { backgroundColor: theme.surface, borderColor: theme.line }]}><Search size={21} color={theme.faint} /><Text style={[styles.emptyTitle, { color: theme.fg }]}>No matching content</Text><Text style={[styles.emptyCopy, { color: theme.muted }]}>Change the search or course filter.</Text></View> : null}
    <View style={[styles.permission, { backgroundColor: theme.primarySoft, borderColor: theme.line }]}><View style={[styles.permissionIcon, { backgroundColor: theme.surface }]}><LockKeyhole size={17} color={theme.primaryStrong} /></View><View style={styles.flex}><Text style={[styles.permissionTitle, { color: theme.primaryStrong }]}>Website-managed catalogue</Text><Text style={[styles.permissionCopy, { color: theme.muted }]}>Uploading, editing and unpublishing notes or packages are intentionally not shown on mobile.</Text></View></View>
  </>;
}

function CreationModal({ request, onClose, onSubmit }: { request: CreateRequest | null; onClose: () => void; onSubmit: (name: string) => void }) {
  const { theme } = useAppTheme(); const [name, setName] = useState('');
  if (!request) return null;
  const config = request.mode === 'course' ? { eyebrow: 'NEW COURSE / EXAM', title: 'Create a learning track', placeholder: 'Example: UPSC', helper: 'This becomes the top level shown during learner setup.' } : request.mode === 'category' ? { eyebrow: 'NEW CATEGORY / LEVEL', title: `Add inside ${request.parentName}`, placeholder: 'Example: Mains', helper: 'Use a stage, level or subcategory learners can recognise.' } : { eyebrow: 'NEW SUBJECT / PHASE', title: `Add inside ${request.parentName}`, placeholder: 'Example: Mathematics', helper: 'Use a subject or phase name exactly as learners should see it.' };
  const close = () => { setName(''); onClose(); };
  const submit = () => { const value = name.trim(); if (!value) return; setName(''); onSubmit(value); };
  return <Modal visible transparent animationType="none" onRequestClose={close}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.modalRoot}><Pressable style={styles.backdrop} onPress={close}><Pressable onPress={(event) => event.stopPropagation()} style={[styles.sheet, { backgroundColor: theme.elevated, borderColor: theme.lineStrong }]}><View style={[styles.sheetHandle, { backgroundColor: theme.lineStrong }]} /><View style={styles.sheetTop}><View style={styles.flex}><Text style={[styles.sheetEyebrow, { color: theme.primary }]}>{config.eyebrow}</Text><Text style={[styles.sheetTitle, { color: theme.fg }]}>{config.title}</Text><Text style={[styles.sheetHelper, { color: theme.muted }]}>{config.helper}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={close} style={[styles.close, { backgroundColor: theme.sunken }]}><X size={18} color={theme.muted} /></Pressable></View><Text style={[styles.fieldLabel, { color: theme.muted }]}>Display name</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder={config.placeholder} placeholderTextColor={theme.faint} style={[styles.input, { backgroundColor: theme.sunken, borderColor: theme.line, color: theme.fg }]} /><View style={[styles.preview, { backgroundColor: theme.primarySoft }]}><GraduationCap size={15} color={theme.primaryStrong} /><Text numberOfLines={1} style={[styles.previewText, { color: theme.primaryStrong }]}>{name.trim() || 'Preview will appear here'}</Text></View><Pressable disabled={!name.trim()} onPress={submit} style={({ pressed }) => [styles.submit, { backgroundColor: theme.primary }, !name.trim() && styles.disabled, pressed && styles.pressed]}><Plus size={16} color={theme.primaryFg} /><Text style={[styles.submitText, { color: theme.primaryFg }]}>Add {request.mode === 'category' ? 'category' : request.mode}</Text></Pressable></Pressable></Pressable></KeyboardAvoidingView></Modal>;
}

const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 }, addCourse: { minHeight: 37, borderRadius: 11, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5 }, addCourseText: { fontFamily: font.bold, fontSize: 9 }, pressed: { opacity: .72, transform: [{ scale: .98 }] },
  pageSwitch: { flexDirection: 'row', borderWidth: 1, borderRadius: 15, padding: 4, gap: 4 }, pageSwitchItem: { flex: 1, height: 40, borderWidth: 1, borderColor: 'transparent', borderRadius: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, pageSwitchText: { fontFamily: font.bold, fontSize: 10 },
  architectureHero: { minHeight: 165, borderRadius: 20, padding: 14, overflow: 'hidden', justifyContent: 'space-between' }, heroOrbit: { position: 'absolute', width: 170, height: 170, borderRadius: 85, borderWidth: 1, borderColor: 'rgba(255,255,255,.08)', right: -62, top: -75 }, heroTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, heroIdentity: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 9 }, heroIcon: { width: 39, height: 39, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,.12)', backgroundColor: 'rgba(255,255,255,.07)', alignItems: 'center', justifyContent: 'center' }, heroEyebrow: { color: '#9FB3FF', fontFamily: font.bold, fontSize: 7, letterSpacing: 1.1 }, heroTitle: { marginTop: 3, color: '#FFF', fontFamily: font.extraBold, fontSize: 18 }, livePill: { minHeight: 25, borderRadius: radius.pill, paddingHorizontal: 8, backgroundColor: 'rgba(103,214,167,.12)', flexDirection: 'row', alignItems: 'center', gap: 4 }, liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#79DFB6' }, liveText: { color: '#79DFB6', fontFamily: font.bold, fontSize: 7 }, heroMetrics: { minHeight: 58, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.09)', paddingTop: 12, flexDirection: 'row', alignItems: 'center' }, heroMetric: { flex: 1, alignItems: 'center' }, heroMetricValue: { color: '#FFF', fontFamily: font.extraBold, fontSize: 18 }, heroMetricLabel: { marginTop: 2, color: '#AEB8D8', fontFamily: font.regular, fontSize: 7 }, heroDivider: { width: 1, height: 31, backgroundColor: 'rgba(255,255,255,.10)' },
  sectionEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.05 }, sectionTitle: { marginTop: 3, fontFamily: font.extraBold, fontSize: 17, letterSpacing: -.3 }, sectionHint: { marginTop: 3, fontFamily: font.regular, fontSize: 8 }, courseTabs: { gap: 8, paddingRight: spacing.lg }, courseTab: { minWidth: 128, minHeight: 62, borderWidth: 1, borderRadius: 15, paddingHorizontal: 11, justifyContent: 'center' }, courseTabTop: { flexDirection: 'row', alignItems: 'center', gap: 6 }, courseTabName: { fontFamily: font.extraBold, fontSize: 12 }, courseTabMeta: { marginTop: 5, fontFamily: font.regular, fontSize: 7 },
  coursePanel: { borderWidth: 1, borderRadius: 20, padding: 13 }, coursePanelTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, courseMark: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, panelEyebrow: { fontFamily: font.bold, fontSize: 7, letterSpacing: 1 }, coursePanelTitle: { marginTop: 2, fontFamily: font.extraBold, fontSize: 17 }, coursePanelMeta: { marginTop: 2, fontFamily: font.regular, fontSize: 8 }, smallAdd: { minHeight: 33, borderRadius: 10, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 }, smallAddText: { fontFamily: font.bold, fontSize: 8 }, categoryList: { marginTop: 13, gap: 8 }, category: { borderWidth: 1, borderRadius: 15, overflow: 'hidden' }, categoryHeader: { minHeight: 65, padding: 9, flexDirection: 'row', alignItems: 'center', gap: 7 }, categoryToggle: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 }, categoryIndex: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, categoryIndexText: { fontFamily: font.extraBold, fontSize: 8 }, categoryLabel: { fontFamily: font.bold, fontSize: 6, letterSpacing: .9 }, categoryTitle: { marginTop: 2, fontFamily: font.bold, fontSize: 11 }, categoryMeta: { marginTop: 2, fontFamily: font.regular, fontSize: 7 }, iconAdd: { width: 33, height: 33, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, subjectList: { borderTopWidth: 1, paddingHorizontal: 9, paddingBottom: 5 }, subjectRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 7 }, subjectIndex: { width: 24, height: 24, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, subjectIndexText: { fontFamily: font.extraBold, fontSize: 7 }, subjectName: { flex: 1, fontFamily: font.semibold, fontSize: 9, lineHeight: 13 }, emptySubjects: { minHeight: 67, alignItems: 'center', justifyContent: 'center', gap: 5 }, emptySubjectsText: { fontFamily: font.regular, fontSize: 8 }, emptyCourse: { minHeight: 130, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { marginTop: 7, fontFamily: font.bold, fontSize: 12 }, emptyCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8 },
  permission: { minHeight: 76, borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9 }, permissionIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, permissionTitle: { fontFamily: font.bold, fontSize: 10 }, permissionCopy: { marginTop: 3, fontFamily: font.regular, fontSize: 8, lineHeight: 13 },
  catalogueHero: { minHeight: 145, borderRadius: 20, padding: 14, overflow: 'hidden', justifyContent: 'space-between' }, catalogueHeroTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, catalogueHeroIcon: { width: 39, height: 39, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(123,221,182,.22)', backgroundColor: 'rgba(123,221,182,.10)', alignItems: 'center', justifyContent: 'center' }, catalogueEyebrow: { color: '#79DFB6', fontFamily: font.bold, fontSize: 7, letterSpacing: 1.05 }, catalogueTitle: { marginTop: 4, color: '#FFF', fontFamily: font.extraBold, fontSize: 16 }, catalogueHint: { marginTop: 3, color: '#AEB8C7', fontFamily: font.regular, fontSize: 7 }, readOnlyDark: { minHeight: 25, borderRadius: radius.pill, borderWidth: 1, borderColor: 'rgba(255,255,255,.12)', backgroundColor: 'rgba(0,0,0,.14)', paddingHorizontal: 7, flexDirection: 'row', alignItems: 'center', gap: 4 }, readOnlyDarkText: { color: '#C9D2DD', fontFamily: font.bold, fontSize: 6 }, catalogueStats: { minHeight: 30, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,.08)', paddingTop: 10, flexDirection: 'row', alignItems: 'center', gap: 7 }, catalogueStat: { color: '#C9D2DD', fontFamily: font.semibold, fontSize: 8 }, catalogueStatDot: { color: '#697789', fontSize: 8 },
  contentSwitch: { flexDirection: 'row', borderWidth: 1, borderRadius: 14, padding: 4, gap: 4 }, contentSwitchItem: { flex: 1, minHeight: 38, borderRadius: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, contentSwitchText: { fontFamily: font.bold, fontSize: 9 }, searchPanel: { borderWidth: 1, borderRadius: 16, padding: 10 }, searchRow: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 8 }, searchInput: { flex: 1, minWidth: 0, paddingVertical: 0, fontFamily: font.regular, fontSize: 11 }, clearText: { fontFamily: font.bold, fontSize: 8 }, searchRule: { height: 1, marginVertical: 8 }, filters: { flexDirection: 'row', gap: 6 }, filter: { flex: 1, minHeight: 30, borderWidth: 1, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center' }, filterText: { fontFamily: font.bold, fontSize: 7 }, catalogueHeading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' }, resultCount: { fontFamily: font.semibold, fontSize: 8 }, paidList: { gap: spacing.sm }, paidRow: { minHeight: 78, borderWidth: 1, borderRadius: 16, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 9 }, paidIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, paidTitle: { fontFamily: font.bold, fontSize: 10 }, paidMeta: { marginTop: 3, fontFamily: font.regular, fontSize: 7 }, publishedPill: { alignSelf: 'flex-start', minHeight: 20, marginTop: 5, borderRadius: radius.pill, paddingHorizontal: 6, flexDirection: 'row', alignItems: 'center', gap: 4 }, publishedDot: { width: 4, height: 4, borderRadius: 2 }, published: { fontFamily: font.bold, fontSize: 6, letterSpacing: .5 }, priceColumn: { alignItems: 'flex-end', gap: 8 }, price: { fontFamily: font.bold, fontSize: 10 }, noPaid: { minHeight: 135, borderWidth: 1, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.68)' }, sheet: { width: '100%', maxWidth: 680, alignSelf: 'center', borderWidth: 1, borderBottomWidth: 0, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing.lg, paddingBottom: 27 }, sheetHandle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 13 }, sheetTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, sheetEyebrow: { fontFamily: font.bold, fontSize: 8, letterSpacing: 1.1 }, sheetTitle: { marginTop: 4, fontFamily: font.extraBold, fontSize: 18, lineHeight: 24 }, sheetHelper: { marginTop: 4, fontFamily: font.regular, fontSize: 8, lineHeight: 13 }, close: { width: 35, height: 35, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, fieldLabel: { marginTop: 17, marginBottom: 6, fontFamily: font.bold, fontSize: 8, letterSpacing: .7 }, input: { minHeight: 47, borderWidth: 1, borderRadius: 12, paddingHorizontal: 11, fontFamily: font.regular, fontSize: 12 }, preview: { minHeight: 40, marginTop: 10, borderRadius: 11, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 7 }, previewText: { flex: 1, fontFamily: font.semibold, fontSize: 9 }, submit: { minHeight: 45, marginTop: 12, borderRadius: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 }, submitText: { fontFamily: font.bold, fontSize: 10 }, disabled: { opacity: .45 },
});
